<?php

namespace Rep98\Venezuela\Database\Seeders;

use Rep98\Venezuela\Models\State;
use Rep98\Venezuela\Models\Municipality;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    public function run()
    {
        $municipalities = [
			["name"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Autonomo Atabapo","state"=>"Amazonas"],
			["name"=>"Autonomo Rio Negro","state"=>"Amazonas"],
			["name"=>"Autonomo Atures","state"=>"Amazonas"],
			["name"=>"Autonomo Autana","state"=>"Amazonas"],
			["name"=>"Autonomo Maroa","state"=>"Amazonas"],
			["name"=>"Autonomo Alto Orinoco","state"=>"Amazonas"],
			["name"=>"Autonomo Manapiare","state"=>"Amazonas"],
			["name"=>"Santa Ana","state"=>"Anzoategui"],
			["name"=>"Francisco De Miranda","state"=>"Anzoategui"],
			["name"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"Sir Arthur Mc Gregor","state"=>"Anzoategui"],
			["name"=>"Juan Antonio Sotillo","state"=>"Anzoategui"],
			["name"=>"Francisco Del Carmen Carvajal","state"=>"Anzoategui"],
			["name"=>"Libertad","state"=>"Anzoategui"],
			["name"=>"Aragua","state"=>"Anzoategui"],
			["name"=>"Fernando De Penalver","state"=>"Anzoategui"],
			["name"=>"San Juan De Capistrano","state"=>"Anzoategui"],
			["name"=>"Anaco","state"=>"Anzoategui"],
			["name"=>"Juan Manuel Cajigal","state"=>"Anzoategui"],
			["name"=>"Independencia","state"=>"Anzoategui"],
			["name"=>"Pedro Maria Freites","state"=>"Anzoategui"],
			["name"=>"Piritu","state"=>"Anzoategui"],
			["name"=>"San Jose De Guanipa","state"=>"Anzoategui"],
			["name"=>"Turistico Diego Bautista Urbaneja","state"=>"Anzoategui"],
			["name"=>"Manuel Ezequiel Bruzual","state"=>"Anzoategui"],
			["name"=>"Guanta","state"=>"Anzoategui"],
			["name"=>"Simon Rodriguez","state"=>"Anzoategui"],
			["name"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"Achaguas","state"=>"Apure"],
			["name"=>"Biruaca","state"=>"Apure"],
			["name"=>"Paez","state"=>"Apure"],
			["name"=>"Muñoz","state"=>"Apure"],
			["name"=>"Romulo Gallegos","state"=>"Apure"],
			["name"=>"San Fernando","state"=>"Apure"],
			["name"=>"Pedro Camejo","state"=>"Apure"],
			["name"=>"Zamora","state"=>"Aragua"],
			["name"=>"Ocumare De La Costa De Oro","state"=>"Aragua"],
			["name"=>"Jose Felix Ribas","state"=>"Aragua"],
			["name"=>"San Casimiro","state"=>"Aragua"],
			["name"=>"Santiago Mariño","state"=>"Aragua"],
			["name"=>"Girardot","state"=>"Aragua"],
			["name"=>"Sucre","state"=>"Aragua"],
			["name"=>"Urdaneta","state"=>"Aragua"],
			["name"=>"Francisco Linares Alcantara","state"=>"Aragua"],
			["name"=>"Jose Rafael Revenga","state"=>"Aragua"],
			["name"=>"Santos Michelena","state"=>"Aragua"],
			["name"=>"Bolivar","state"=>"Aragua"],
			["name"=>"San Sebastian","state"=>"Aragua"],
			["name"=>"Tovar","state"=>"Aragua"],
			["name"=>"Libertador","state"=>"Aragua"],
			["name"=>"Mario Briceño Iragorry","state"=>"Aragua"],
			["name"=>"Jose Angel Lamas","state"=>"Aragua"],
			["name"=>"Camatagua","state"=>"Aragua"],
			["name"=>"Andre Eloy Blanco","state"=>"Barinas"],
			["name"=>"Ezequiel Zamora","state"=>"Barinas"],
			["name"=>"Antonio Jose De Sucre","state"=>"Barinas"],
			["name"=>"Barinas","state"=>"Barinas"],
			["name"=>"Rojas","state"=>"Barinas"],
			["name"=>"Sosa","state"=>"Barinas"],
			["name"=>"Arismendi","state"=>"Barinas"],
			["name"=>"Cruz Paredes","state"=>"Barinas"],
			["name"=>"Pedraza","state"=>"Barinas"],
			["name"=>"Obispos","state"=>"Barinas"],
			["name"=>"Alberto Arvelo Torrealba","state"=>"Barinas"],
			["name"=>"Bolivar","state"=>"Barinas"],
			["name"=>"Gran Sabana","state"=>"Bolivar"],
			["name"=>"Heres","state"=>"Bolivar"],
			["name"=>"Sucre","state"=>"Bolivar"],
			["name"=>"Padre Pedro Chien","state"=>"Bolivar"],
			["name"=>"Piar","state"=>"Bolivar"],
			["name"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"Sifontes","state"=>"Bolivar"],
			["name"=>"Roscio","state"=>"Bolivar"],
			["name"=>"El Callao","state"=>"Bolivar"],
			["name"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Bolivariano Angostura","state"=>"Bolivar"],
			["name"=>"Miranda","state"=>"Carabobo"],
			["name"=>"Bejuma","state"=>"Carabobo"],
			["name"=>"San Diego","state"=>"Carabobo"],
			["name"=>"Diego Ibarra","state"=>"Carabobo"],
			["name"=>"Juan Jose Mora","state"=>"Carabobo"],
			["name"=>"Carlos Arvelo","state"=>"Carabobo"],
			["name"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Naguanagua","state"=>"Carabobo"],
			["name"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Libertador","state"=>"Carabobo"],
			["name"=>"Los Guayos","state"=>"Carabobo"],
			["name"=>"Guacara","state"=>"Carabobo"],
			["name"=>"Montalban","state"=>"Carabobo"],
			["name"=>"San Joaquin","state"=>"Carabobo"],
			["name"=>"Pao De San Juan Bautista","state"=>"Cojedes"],
			["name"=>"Romulo Gallegos","state"=>"Cojedes"],
			["name"=>"Ezequiel Zamora","state"=>"Cojedes"],
			["name"=>"Ricaurte","state"=>"Cojedes"],
			["name"=>"Tinaco","state"=>"Cojedes"],
			["name"=>"Lima Blanco","state"=>"Cojedes"],
			["name"=>"Tinaquillo","state"=>"Cojedes"],
			["name"=>"Anzoategui","state"=>"Cojedes"],
			["name"=>"Girardot","state"=>"Cojedes"],
			["name"=>"Casacoima","state"=>"Delta Amacuro"],
			["name"=>"Pedernales","state"=>"Delta Amacuro"],
			["name"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"Dabajuro","state"=>"Falcon"],
			["name"=>"Democracia","state"=>"Falcon"],
			["name"=>"Falcon","state"=>"Falcon"],
			["name"=>"Carirubana","state"=>"Falcon"],
			["name"=>"Colina","state"=>"Falcon"],
			["name"=>"Federacion","state"=>"Falcon"],
			["name"=>"Mauroa","state"=>"Falcon"],
			["name"=>"Acosta","state"=>"Falcon"],
			["name"=>"Miranda","state"=>"Falcon"],
			["name"=>"Monseñor Iturriza","state"=>"Falcon"],
			["name"=>"Piritu","state"=>"Falcon"],
			["name"=>"Palmasola","state"=>"Falcon"],
			["name"=>"Silva","state"=>"Falcon"],
			["name"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Jacura","state"=>"Falcon"],
			["name"=>"San Francisco","state"=>"Falcon"],
			["name"=>"Tocopero","state"=>"Falcon"],
			["name"=>"Urumaco","state"=>"Falcon"],
			["name"=>"Zamora","state"=>"Falcon"],
			["name"=>"Petit","state"=>"Falcon"],
			["name"=>"Sucre","state"=>"Falcon"],
			["name"=>"Union","state"=>"Falcon"],
			["name"=>"Bolivar","state"=>"Falcon"],
			["name"=>"Cacique Manuare","state"=>"Falcon"],
			["name"=>"Los Taques","state"=>"Falcon"],
			["name"=>"San Jose De Guaribe","state"=>"Guarico"],
			["name"=>"Camaguan","state"=>"Guarico"],
			["name"=>"Julian Mellado","state"=>"Guarico"],
			["name"=>"Santa Maria De Ipire","state"=>"Guarico"],
			["name"=>"Chaguaramas","state"=>"Guarico"],
			["name"=>"San Geronimo De Guayabal","state"=>"Guarico"],
			["name"=>"Juan German Roscio","state"=>"Guarico"],
			["name"=>"Jose Felix Rivas","state"=>"Guarico"],
			["name"=>"Las Mercedes","state"=>"Guarico"],
			["name"=>"Pedro Zaraza","state"=>"Guarico"],
			["name"=>"Ortiz","state"=>"Guarico"],
			["name"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"Leonardo Infante","state"=>"Guarico"],
			["name"=>"Francisco De Miranda","state"=>"Guarico"],
			["name"=>"El Socorro","state"=>"Guarico"],
			["name"=>"Jimenez","state"=>"Lara"],
			["name"=>"Urdaneta","state"=>"Lara"],
			["name"=>"Andre Eloy Blanco","state"=>"Lara"],
			["name"=>"Simon Planas","state"=>"Lara"],
			["name"=>"Iribarren","state"=>"Lara"],
			["name"=>"Crespo","state"=>"Lara"],
			["name"=>"Torres","state"=>"Lara"],
			["name"=>"Moran","state"=>"Lara"],
			["name"=>"Palavecino","state"=>"Lara"],
			["name"=>"Aricagua","state"=>"Merida"],
			["name"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Caracciolo Parra Olmedo","state"=>"Merida"],
			["name"=>"Antonio Pinto  Salinas","state"=>"Merida"],
			["name"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Libertador","state"=>"Merida"],
			["name"=>"Obispo Ramos De Lora","state"=>"Merida"],
			["name"=>"Guaraque","state"=>"Merida"],
			["name"=>"Pueblo Llano","state"=>"Merida"],
			["name"=>"Rivas Davila","state"=>"Merida"],
			["name"=>"Zea","state"=>"Merida"],
			["name"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"Miranda","state"=>"Merida"],
			["name"=>"Justo Briceño","state"=>"Merida"],
			["name"=>"Tovar","state"=>"Merida"],
			["name"=>"Tulio Febres Cordero","state"=>"Merida"],
			["name"=>"Padre Noguera","state"=>"Merida"],
			["name"=>"Sucre","state"=>"Merida"],
			["name"=>"Santos Marquina","state"=>"Merida"],
			["name"=>"Cardenal Quintero","state"=>"Merida"],
			["name"=>"Andre Bello","state"=>"Merida"],
			["name"=>"Julio Cear Salas","state"=>"Merida"],
			["name"=>"Rangel","state"=>"Merida"],
			["name"=>"Baruta","state"=>"Bolivariano De Miranda"],
			["name"=>"Carrizal","state"=>"Bolivariano De Miranda"],
			["name"=>"Lander","state"=>"Bolivariano De Miranda"],
			["name"=>"El Hatillo","state"=>"Bolivariano De Miranda"],
			["name"=>"Los Salias","state"=>"Bolivariano De Miranda"],
			["name"=>"Buroz","state"=>"Bolivariano De Miranda"],
			["name"=>"Zamora","state"=>"Bolivariano De Miranda"],
			["name"=>"Pedro  Gual","state"=>"Bolivariano De Miranda"],
			["name"=>"Cristobal Rojas","state"=>"Bolivariano De Miranda"],
			["name"=>"Urdaneta","state"=>"Bolivariano De Miranda"],
			["name"=>"Andre Bello","state"=>"Bolivariano De Miranda"],
			["name"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Brion","state"=>"Bolivariano De Miranda"],
			["name"=>"Chacao","state"=>"Bolivariano De Miranda"],
			["name"=>"Plaza","state"=>"Bolivariano De Miranda"],
			["name"=>"Paz Castillo","state"=>"Bolivariano De Miranda"],
			["name"=>"Independencia","state"=>"Bolivariano De Miranda"],
			["name"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"Paez","state"=>"Bolivariano De Miranda"],
			["name"=>"Simon Bolivar","state"=>"Bolivariano De Miranda"],
			["name"=>"Sucre","state"=>"Bolivariano De Miranda"],
			["name"=>"Aguasay","state"=>"Monagas"],
			["name"=>"Caripe","state"=>"Monagas"],
			["name"=>"Ezequiel Zamora","state"=>"Monagas"],
			["name"=>"Maturin","state"=>"Monagas"],
			["name"=>"Libertador","state"=>"Monagas"],
			["name"=>"Santa Barbara","state"=>"Monagas"],
			["name"=>"Sotillo","state"=>"Monagas"],
			["name"=>"Cedeño","state"=>"Monagas"],
			["name"=>"Bolivar","state"=>"Monagas"],
			["name"=>"Piar","state"=>"Monagas"],
			["name"=>"Uracoa","state"=>"Monagas"],
			["name"=>"Acosta","state"=>"Monagas"],
			["name"=>"Punceres","state"=>"Monagas"],
			["name"=>"Arismendi","state"=>"Nueva Esparta"],
			["name"=>"Gomez","state"=>"Nueva Esparta"],
			["name"=>"Marcano","state"=>"Nueva Esparta"],
			["name"=>"Garcia","state"=>"Nueva Esparta"],
			["name"=>"Diaz","state"=>"Nueva Esparta"],
			["name"=>"Tubores","state"=>"Nueva Esparta"],
			["name"=>"Maneiro","state"=>"Nueva Esparta"],
			["name"=>"Villalba","state"=>"Nueva Esparta"],
			["name"=>"Antolin Del Campo","state"=>"Nueva Esparta"],
			["name"=>"Mariño","state"=>"Nueva Esparta"],
			["name"=>"Peninsula De Macanao","state"=>"Nueva Esparta"],
			["name"=>"Araure","state"=>"Portuguesa"],
			["name"=>"Santa  Rosalia","state"=>"Portuguesa"],
			["name"=>"Guanarito","state"=>"Portuguesa"],
			["name"=>"Guanare","state"=>"Portuguesa"],
			["name"=>"San Genaro De Boconoito","state"=>"Portuguesa"],
			["name"=>"San Rafael De Onoto","state"=>"Portuguesa"],
			["name"=>"Monseñor Jose Vicente De Unda","state"=>"Portuguesa"],
			["name"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"Papelon","state"=>"Portuguesa"],
			["name"=>"Agua Blanca","state"=>"Portuguesa"],
			["name"=>"Esteller","state"=>"Portuguesa"],
			["name"=>"Turen","state"=>"Portuguesa"],
			["name"=>"Paez","state"=>"Portuguesa"],
			["name"=>"Ospino","state"=>"Portuguesa"],
			["name"=>"Andre Eloy Blanco","state"=>"Sucre"],
			["name"=>"Montes","state"=>"Sucre"],
			["name"=>"Bermudez","state"=>"Sucre"],
			["name"=>"Andre Mata","state"=>"Sucre"],
			["name"=>"Benitez","state"=>"Sucre"],
			["name"=>"Mariño","state"=>"Sucre"],
			["name"=>"Mejia","state"=>"Sucre"],
			["name"=>"Ribero","state"=>"Sucre"],
			["name"=>"Libertador","state"=>"Sucre"],
			["name"=>"Bolivar","state"=>"Sucre"],
			["name"=>"Sucre","state"=>"Sucre"],
			["name"=>"Arismendi","state"=>"Sucre"],
			["name"=>"Cruz Salmeron Acosta","state"=>"Sucre"],
			["name"=>"Valdez","state"=>"Sucre"],
			["name"=>"Cajigal","state"=>"Sucre"],
			["name"=>"Libertador","state"=>"Tachira"],
			["name"=>"Libertad","state"=>"Tachira"],
			["name"=>"Cordoba","state"=>"Tachira"],
			["name"=>"Michelena","state"=>"Tachira"],
			["name"=>"Rafael Urdaneta","state"=>"Tachira"],
			["name"=>"Antonio Romulo Costa","state"=>"Tachira"],
			["name"=>"Simon Rodriguez","state"=>"Tachira"],
			["name"=>"San Judas Tadeo","state"=>"Tachira"],
			["name"=>"Cardenas","state"=>"Tachira"],
			["name"=>"Jose Maria Vargas","state"=>"Tachira"],
			["name"=>"Sucre","state"=>"Tachira"],
			["name"=>"Bolivar","state"=>"Tachira"],
			["name"=>"Panamericano","state"=>"Tachira"],
			["name"=>"Ayacucho","state"=>"Tachira"],
			["name"=>"Guasimos","state"=>"Tachira"],
			["name"=>"Andre Bello","state"=>"Tachira"],
			["name"=>"Fernandez Feo","state"=>"Tachira"],
			["name"=>"Jauregui","state"=>"Tachira"],
			["name"=>"Junin","state"=>"Tachira"],
			["name"=>"Samuel Dario Maldonado","state"=>"Tachira"],
			["name"=>"Uribante","state"=>"Tachira"],
			["name"=>"Francisco De Miranda","state"=>"Tachira"],
			["name"=>"Torbes","state"=>"Tachira"],
			["name"=>"Garcia De Hevia","state"=>"Tachira"],
			["name"=>"Lobatera","state"=>"Tachira"],
			["name"=>"San Cristobal","state"=>"Tachira"],
			["name"=>"Independencia","state"=>"Tachira"],
			["name"=>"Seboruco","state"=>"Tachira"],
			["name"=>"Pedro Maria Ureña","state"=>"Tachira"],
			["name"=>"Pampan","state"=>"Trujillo"],
			["name"=>"Sucre","state"=>"Trujillo"],
			["name"=>"Andre Bello","state"=>"Trujillo"],
			["name"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"Jose Felipe Marquez Cañizales","state"=>"Trujillo"],
			["name"=>"Miranda","state"=>"Trujillo"],
			["name"=>"Valera","state"=>"Trujillo"],
			["name"=>"Motatan","state"=>"Trujillo"],
			["name"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Monte Carmelo","state"=>"Trujillo"],
			["name"=>"San Rafael De Carvajal","state"=>"Trujillo"],
			["name"=>"Carache","state"=>"Trujillo"],
			["name"=>"Escuque","state"=>"Trujillo"],
			["name"=>"Juan Vicente Campo Elias","state"=>"Trujillo"],
			["name"=>"La Ceiba","state"=>"Trujillo"],
			["name"=>"Rafael Rangel","state"=>"Trujillo"],
			["name"=>"Bolivar","state"=>"Trujillo"],
			["name"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"Pampanito","state"=>"Trujillo"],
			["name"=>"Manuel Monge","state"=>"Yaracuy"],
			["name"=>"Cocorote","state"=>"Yaracuy"],
			["name"=>"Veroes","state"=>"Yaracuy"],
			["name"=>"La Trinidad","state"=>"Yaracuy"],
			["name"=>"Nirgua","state"=>"Yaracuy"],
			["name"=>"Bruzual","state"=>"Yaracuy"],
			["name"=>"Peña","state"=>"Yaracuy"],
			["name"=>"Independencia","state"=>"Yaracuy"],
			["name"=>"Urachiche","state"=>"Yaracuy"],
			["name"=>"Sucre","state"=>"Yaracuy"],
			["name"=>"Bolivar","state"=>"Yaracuy"],
			["name"=>"Aristides Bastidas","state"=>"Yaracuy"],
			["name"=>"Jose Antonio Paez","state"=>"Yaracuy"],
			["name"=>"San Felipe","state"=>"Yaracuy"],
			["name"=>"Jesus Maria Semprum","state"=>"Zulia"],
			["name"=>"Mara","state"=>"Zulia"],
			["name"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"Santa Rita","state"=>"Zulia"],
			["name"=>"Machiques De Perija","state"=>"Zulia"],
			["name"=>"Valmore Rodriguez","state"=>"Zulia"],
			["name"=>"Colon","state"=>"Zulia"],
			["name"=>"Cabimas","state"=>"Zulia"],
			["name"=>"Rosario De Perija","state"=>"Zulia"],
			["name"=>"Indigena Bolivariano Guajira","state"=>"Zulia"],
			["name"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Almirante Padilla","state"=>"Zulia"],
			["name"=>"Jesus Enrique Lossada","state"=>"Zulia"],
			["name"=>"Miranda","state"=>"Zulia"],
			["name"=>"Baralt","state"=>"Zulia"],
			["name"=>"Catatumbo","state"=>"Zulia"],
			["name"=>"La Cañada De Urdaneta","state"=>"Zulia"],
			["name"=>"Sucre","state"=>"Zulia"],
			["name"=>"Simon Bolivar","state"=>"Zulia"],
			["name"=>"Francisco Javier Pulgar","state"=>"Zulia"],
			["name"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Vargas","state"=>"La Guaira"]
		];

        foreach ($municipalities as $municipality) {
            $state = State::where('name', $municipality['state'])->first();
            Municipality::create([
                'name' => $municipality['name'],
                'state_id' => $state->id
            ]);
        }
    }
}