<?php

namespace Rep98\Venezuela\Database\Seeders;

use Rep98\Venezuela\Models\State;
use Rep98\Venezuela\Models\Municipality;
use Rep98\Venezuela\Models\Parish;
use Illuminate\Database\Seeder;

class ParishSeeder extends Seeder
{
    public function run()
    {
        $parishes = [
			["name"=>"Altagracia","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Antimano","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Candelaria","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Caricuao","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Catedral","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Coche","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"El Junquito","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"El Paraiso","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"El Recreo","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"El Valle","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"La Pastora","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"La Vega","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Macarao","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"San Agustin","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"San Bernardino","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"San Jose","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"San Juan","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"San Pedro","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Santa Rosalia","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Santa Teresa","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Sucre","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"23 De Enero","municipality"=>"Libertador","state"=>"Distrito Capital"],
			["name"=>"Ucata","municipality"=>"Autonomo Atabapo","state"=>"Amazonas"],
			["name"=>"Yacapana","municipality"=>"Autonomo Atabapo","state"=>"Amazonas"],
			["name"=>"San Carlos De Río Negro (Capital)","municipality"=>"Autonomo Rio Negro","state"=>"Amazonas"],
			["name"=>"Fernando Giron Tovar","municipality"=>"Autonomo Atures","state"=>"Amazonas"],
			["name"=>"Luis Alberto Gomez","municipality"=>"Autonomo Atures","state"=>"Amazonas"],
			["name"=>"Parhueña","municipality"=>"Autonomo Atures","state"=>"Amazonas"],
			["name"=>"Platanillal","municipality"=>"Autonomo Atures","state"=>"Amazonas"],
			["name"=>"Samariapo","municipality"=>"Autonomo Autana","state"=>"Amazonas"],
			["name"=>"Guayapo","municipality"=>"Autonomo Autana","state"=>"Amazonas"],
			["name"=>"Victorino","municipality"=>"Autonomo Maroa","state"=>"Amazonas"],
			["name"=>"Comunidad","municipality"=>"Autonomo Maroa","state"=>"Amazonas"],
			["name"=>"Huachamacare","municipality"=>"Autonomo Alto Orinoco","state"=>"Amazonas"],
			["name"=>"Alto Ventuari","municipality"=>"Autonomo Manapiare","state"=>"Amazonas"],
			["name"=>"Medio Ventuari","municipality"=>"Autonomo Manapiare","state"=>"Amazonas"],
			["name"=>"Capital Santa Ana","municipality"=>"Santa Ana","state"=>"Anzoategui"],
			["name"=>"Pueblo Nuevo","municipality"=>"Santa Ana","state"=>"Anzoategui"],
			["name"=>"Capital Francisco De Miranda","municipality"=>"Francisco De Miranda","state"=>"Anzoategui"],
			["name"=>"Atapirire","municipality"=>"Francisco De Miranda","state"=>"Anzoategui"],
			["name"=>"Boca Del Pao","municipality"=>"Francisco De Miranda","state"=>"Anzoategui"],
			["name"=>"El Pao","municipality"=>"Francisco De Miranda","state"=>"Anzoategui"],
			["name"=>"El Carmen","municipality"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"San Cristobal","municipality"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"Bergantin","municipality"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"Caigua","municipality"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"El Pilar","municipality"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"Naricual","municipality"=>"Simon Bolivar","state"=>"Anzoategui"],
			["name"=>"Capital Sir Arthur Mc Gregor","municipality"=>"Sir Arthur Mc Gregor","state"=>"Anzoategui"],
			["name"=>"Tomas Alfaro Calatrava","municipality"=>"Sir Arthur Mc Gregor","state"=>"Anzoategui"],
			["name"=>"Pozuelos","municipality"=>"Juan Antonio Sotillo","state"=>"Anzoategui"],
			["name"=>"Capital Puerto La Cruz","municipality"=>"Juan Antonio Sotillo","state"=>"Anzoategui"],
			["name"=>"Capital Francisco Del Carmen Carvajal","municipality"=>"Francisco Del Carmen Carvajal","state"=>"Anzoategui"],
			["name"=>"Santa Barbara","municipality"=>"Francisco Del Carmen Carvajal","state"=>"Anzoategui"],
			["name"=>"Capital Libertad","municipality"=>"Libertad","state"=>"Anzoategui"],
			["name"=>"El Carito","municipality"=>"Libertad","state"=>"Anzoategui"],
			["name"=>"Santa Ine","municipality"=>"Libertad","state"=>"Anzoategui"],
			["name"=>"Capital Aragua","municipality"=>"Aragua","state"=>"Anzoategui"],
			["name"=>"Cachipo","municipality"=>"Aragua","state"=>"Anzoategui"],
			["name"=>"Capital Fernando De Penalver","municipality"=>"Fernando De Penalver","state"=>"Anzoategui"],
			["name"=>"San Miguel","municipality"=>"Fernando De Penalver","state"=>"Anzoategui"],
			["name"=>"Sucre","municipality"=>"Fernando De Penalver","state"=>"Anzoategui"],
			["name"=>"Capital San Juan De Capistrano","municipality"=>"San Juan De Capistrano","state"=>"Anzoategui"],
			["name"=>"Boca De Chavez","municipality"=>"San Juan De Capistrano","state"=>"Anzoategui"],
			["name"=>"Capital Anaco","municipality"=>"Anaco","state"=>"Anzoategui"],
			["name"=>"San Joaquin","municipality"=>"Anaco","state"=>"Anzoategui"],
			["name"=>"Buena Vista","municipality"=>"Anaco","state"=>"Anzoategui"],
			["name"=>"Capital Juan Manuel Cajigal","municipality"=>"Juan Manuel Cajigal","state"=>"Anzoategui"],
			["name"=>"San Pablo","municipality"=>"Juan Manuel Cajigal","state"=>"Anzoategui"],
			["name"=>"Capital Independencia","municipality"=>"Independencia","state"=>"Anzoategui"],
			["name"=>"Mamo","municipality"=>"Independencia","state"=>"Anzoategui"],
			["name"=>"Capital Pedro Maria Freites","municipality"=>"Pedro Maria Freites","state"=>"Anzoategui"],
			["name"=>"Libertador","municipality"=>"Pedro Maria Freites","state"=>"Anzoategui"],
			["name"=>"Santa Rosa","municipality"=>"Pedro Maria Freites","state"=>"Anzoategui"],
			["name"=>"Urica","municipality"=>"Pedro Maria Freites","state"=>"Anzoategui"],
			["name"=>"Capital Piritu","municipality"=>"Piritu","state"=>"Anzoategui"],
			["name"=>"San Francisco","municipality"=>"Piritu","state"=>"Anzoategui"],
			["name"=>"No Tiene Parroquia (Capital El Tigrito)","municipality"=>"San Jose De Guanipa","state"=>"Anzoategui"],
			["name"=>"Capital Diego Bautista Urbaneja","municipality"=>"Turistico Diego Bautista Urbaneja","state"=>"Anzoategui"],
			["name"=>"El Morro","municipality"=>"Turistico Diego Bautista Urbaneja","state"=>"Anzoategui"],
			["name"=>"Capital Manuel Ezequiel Bruzual","municipality"=>"Manuel Ezequiel Bruzual","state"=>"Anzoategui"],
			["name"=>"Guanape","municipality"=>"Manuel Ezequiel Bruzual","state"=>"Anzoategui"],
			["name"=>"Sabana De Uchire","municipality"=>"Manuel Ezequiel Bruzual","state"=>"Anzoategui"],
			["name"=>"Capital Guanta","municipality"=>"Guanta","state"=>"Anzoategui"],
			["name"=>"Chorreron","municipality"=>"Guanta","state"=>"Anzoategui"],
			["name"=>"Edmundo Barrios","municipality"=>"Simon Rodriguez","state"=>"Anzoategui"],
			["name"=>"Capital Jose Gregorio Monagas","municipality"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"Piar","municipality"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"San Diego De Cabrutica","municipality"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"Santa Clara","municipality"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"Uverito","municipality"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"Zuata","municipality"=>"Jose Gregorio Monagas","state"=>"Anzoategui"],
			["name"=>"Urbana Achaguas","municipality"=>"Achaguas","state"=>"Apure"],
			["name"=>"Apurito","municipality"=>"Achaguas","state"=>"Apure"],
			["name"=>"El Yagual","municipality"=>"Achaguas","state"=>"Apure"],
			["name"=>"Guachara","municipality"=>"Achaguas","state"=>"Apure"],
			["name"=>"Mucuritas","municipality"=>"Achaguas","state"=>"Apure"],
			["name"=>"Queseras Del Medio","municipality"=>"Achaguas","state"=>"Apure"],
			["name"=>"Urbana Biruaca","municipality"=>"Biruaca","state"=>"Apure"],
			["name"=>"Urbana Guasdualito","municipality"=>"Paez","state"=>"Apure"],
			["name"=>"Aramendi","municipality"=>"Paez","state"=>"Apure"],
			["name"=>"El Amparo","municipality"=>"Paez","state"=>"Apure"],
			["name"=>"San Camilo","municipality"=>"Paez","state"=>"Apure"],
			["name"=>"Urdaneta","municipality"=>"Paez","state"=>"Apure"],
			["name"=>"Urbana Bruzual","municipality"=>"Muñoz","state"=>"Apure"],
			["name"=>"Mantecal","municipality"=>"Muñoz","state"=>"Apure"],
			["name"=>"Quintero","municipality"=>"Muñoz","state"=>"Apure"],
			["name"=>"San Vicente","municipality"=>"Muñoz","state"=>"Apure"],
			["name"=>"Rincon Hondo","municipality"=>"Muñoz","state"=>"Apure"],
			["name"=>"Urbana Elorza","municipality"=>"Romulo Gallegos","state"=>"Apure"],
			["name"=>"La Trinidad","municipality"=>"Romulo Gallegos","state"=>"Apure"],
			["name"=>"Urbana San Fernando","municipality"=>"San Fernando","state"=>"Apure"],
			["name"=>"El Recreo","municipality"=>"San Fernando","state"=>"Apure"],
			["name"=>"Peñalver","municipality"=>"San Fernando","state"=>"Apure"],
			["name"=>"San Rafael De Atamaica","municipality"=>"San Fernando","state"=>"Apure"],
			["name"=>"Urbana San Juan De Payara","municipality"=>"Pedro Camejo","state"=>"Apure"],
			["name"=>"Codazzi","municipality"=>"Pedro Camejo","state"=>"Apure"],
			["name"=>"Cunaviche","municipality"=>"Pedro Camejo","state"=>"Apure"],
			["name"=>"Zamora","municipality"=>"Zamora","state"=>"Aragua"],
			["name"=>"No Urbana Magdaleno","municipality"=>"Zamora","state"=>"Aragua"],
			["name"=>"No Urbana San Francisco De Asis","municipality"=>"Zamora","state"=>"Aragua"],
			["name"=>"No Urbana Valles De Tucutunemo","municipality"=>"Zamora","state"=>"Aragua"],
			["name"=>"No Urbana Augusto Mijares","municipality"=>"Zamora","state"=>"Aragua"],
			["name"=>"No Tiene Parroquia (Capital Ocumare De La Costa)","municipality"=>"Ocumare De La Costa De Oro","state"=>"Aragua"],
			["name"=>"Urbana Juan Vicente Bolivar Y Ponte","municipality"=>"Jose Felix Ribas","state"=>"Aragua"],
			["name"=>"Urbana Castor Nieves Rios","municipality"=>"Jose Felix Ribas","state"=>"Aragua"],
			["name"=>"No Urbana Las Guacamayas","municipality"=>"Jose Felix Ribas","state"=>"Aragua"],
			["name"=>"No Urbana Pao De Zarate","municipality"=>"Jose Felix Ribas","state"=>"Aragua"],
			["name"=>"No Urbana Zuata","municipality"=>"Jose Felix Ribas","state"=>"Aragua"],
			["name"=>"San Casimiro","municipality"=>"San Casimiro","state"=>"Aragua"],
			["name"=>"No Urbana Guiripa","municipality"=>"San Casimiro","state"=>"Aragua"],
			["name"=>"No Urbana Ollas De Caramacate","municipality"=>"San Casimiro","state"=>"Aragua"],
			["name"=>"No Urbana Valle Morin","municipality"=>"San Casimiro","state"=>"Aragua"],
			["name"=>"Santiago Mariño","municipality"=>"Santiago Mariño","state"=>"Aragua"],
			["name"=>"No Urbana Arevalo Aponte","municipality"=>"Santiago Mariño","state"=>"Aragua"],
			["name"=>"No Urbana Chuao","municipality"=>"Santiago Mariño","state"=>"Aragua"],
			["name"=>"No Urbana Saman De Guere","municipality"=>"Santiago Mariño","state"=>"Aragua"],
			["name"=>"No Urbana Alfredo Pacheco Miranda","municipality"=>"Santiago Mariño","state"=>"Aragua"],
			["name"=>"No Urbana Choroni","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Las Delicias","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Madre Maria De San Jose","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Joaquin Crespo","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Pedro Jose Ovalles","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Jose Casanova Godoy","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Andres Eloy Blanco","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Urbana Los Tacariguas","municipality"=>"Girardot","state"=>"Aragua"],
			["name"=>"Sucre","municipality"=>"Sucre","state"=>"Aragua"],
			["name"=>"No Urbana Bella Vista","municipality"=>"Sucre","state"=>"Aragua"],
			["name"=>"Urdaneta","municipality"=>"Urdaneta","state"=>"Aragua"],
			["name"=>"No Urbana Las Peñitas","municipality"=>"Urdaneta","state"=>"Aragua"],
			["name"=>"No Urbana San Francisco De Cara","municipality"=>"Urdaneta","state"=>"Aragua"],
			["name"=>"No Urbana Taguay","municipality"=>"Urdaneta","state"=>"Aragua"],
			["name"=>"Francisco Linares Alcantara","municipality"=>"Francisco Linares Alcantara","state"=>"Aragua"],
			["name"=>"No Urbana Francisco De Miranda","municipality"=>"Francisco Linares Alcantara","state"=>"Aragua"],
			["name"=>"No Urbana Monseñor Feliciano Gonzalez","municipality"=>"Francisco Linares Alcantara","state"=>"Aragua"],
			["name"=>"No Tiene Parroquia (Capital El Consejo)","municipality"=>"Jose Rafael Revenga","state"=>"Aragua"],
			["name"=>"Santos Michelena","municipality"=>"Santos Michelena","state"=>"Aragua"],
			["name"=>"No Urbana Tiara","municipality"=>"Santos Michelena","state"=>"Aragua"],
			["name"=>"No Tiene Parroquia (Capital San Mateo)","municipality"=>"Bolivar","state"=>"Aragua"],
			["name"=>"No Tiene Parroquia (Capital San Sebastian)","municipality"=>"San Sebastian","state"=>"Aragua"],
			["name"=>"No Tiene Parroquia (Capital La Colonia Tovar)","municipality"=>"Tovar","state"=>"Aragua"],
			["name"=>"Libertador","municipality"=>"Libertador","state"=>"Aragua"],
			["name"=>"No Urbana San Martin De Porres","municipality"=>"Libertador","state"=>"Aragua"],
			["name"=>"Mario Briceño Iragorry","municipality"=>"Mario Briceño Iragorry","state"=>"Aragua"],
			["name"=>"Urbana Caña De Azucar","municipality"=>"Mario Briceño Iragorry","state"=>"Aragua"],
			["name"=>"No Tiene Parroquia (Capital Santa Cruz)","municipality"=>"Jose Angel Lamas","state"=>"Aragua"],
			["name"=>"Camatagua","municipality"=>"Camatagua","state"=>"Aragua"],
			["name"=>"No Urbana Carmen De Cura","municipality"=>"Camatagua","state"=>"Aragua"],
			["name"=>"El Canton","municipality"=>"Andre Eloy Blanco","state"=>"Barinas"],
			["name"=>"Santa Cruz De Guacas","municipality"=>"Andre Eloy Blanco","state"=>"Barinas"],
			["name"=>"Puerto Vivas","municipality"=>"Andre Eloy Blanco","state"=>"Barinas"],
			["name"=>"Santa Barbara","municipality"=>"Ezequiel Zamora","state"=>"Barinas"],
			["name"=>"Jose Ignacio Pumar","municipality"=>"Ezequiel Zamora","state"=>"Barinas"],
			["name"=>"Pedro Briceño Mendez","municipality"=>"Ezequiel Zamora","state"=>"Barinas"],
			["name"=>"Ramon Ignacio Mendez","municipality"=>"Ezequiel Zamora","state"=>"Barinas"],
			["name"=>"Ticoporo","municipality"=>"Antonio Jose De Sucre","state"=>"Barinas"],
			["name"=>"Andres Bello","municipality"=>"Antonio Jose De Sucre","state"=>"Barinas"],
			["name"=>"Nicolas Pulido","municipality"=>"Antonio Jose De Sucre","state"=>"Barinas"],
			["name"=>"Barinas","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Alfredo Arvelo Larriva","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"San Silvestre","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Santa Ines","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Santa Lucia","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Torunos","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"El Carmen","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Romulo Betancourt","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Corazon De Jesus","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Ramon Ignacio Mendez","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Alto Barinas","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Manuel Palacio Fajardo","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Juan Antonio Rodriguez Dominguez","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Dominga Ortiz De Paez","municipality"=>"Barinas","state"=>"Barinas"],
			["name"=>"Libertad","municipality"=>"Rojas","state"=>"Barinas"],
			["name"=>"Dolores","municipality"=>"Rojas","state"=>"Barinas"],
			["name"=>"Palacios Fajardo","municipality"=>"Rojas","state"=>"Barinas"],
			["name"=>"Santa Rosa","municipality"=>"Rojas","state"=>"Barinas"],
			["name"=>"Ciudad De Nutrias","municipality"=>"Sosa","state"=>"Barinas"],
			["name"=>"El Regalo","municipality"=>"Sosa","state"=>"Barinas"],
			["name"=>"Puerto De Nutrias","municipality"=>"Sosa","state"=>"Barinas"],
			["name"=>"Santa Catalina","municipality"=>"Sosa","state"=>"Barinas"],
			["name"=>"Arismendi","municipality"=>"Arismendi","state"=>"Barinas"],
			["name"=>"Guadarrama","municipality"=>"Arismendi","state"=>"Barinas"],
			["name"=>"La Union","municipality"=>"Arismendi","state"=>"Barinas"],
			["name"=>"San Antonio","municipality"=>"Arismendi","state"=>"Barinas"],
			["name"=>"Barrancas","municipality"=>"Cruz Paredes","state"=>"Barinas"],
			["name"=>"El Socorro","municipality"=>"Cruz Paredes","state"=>"Barinas"],
			["name"=>"Masparrito","municipality"=>"Cruz Paredes","state"=>"Barinas"],
			["name"=>"Ciudad Bolivia","municipality"=>"Pedraza","state"=>"Barinas"],
			["name"=>"Ignacio Briceño","municipality"=>"Pedraza","state"=>"Barinas"],
			["name"=>"Jose Felix Ribas","municipality"=>"Pedraza","state"=>"Barinas"],
			["name"=>"Paez","municipality"=>"Pedraza","state"=>"Barinas"],
			["name"=>"Obispos","municipality"=>"Obispos","state"=>"Barinas"],
			["name"=>"El Real","municipality"=>"Obispos","state"=>"Barinas"],
			["name"=>"La Luz","municipality"=>"Obispos","state"=>"Barinas"],
			["name"=>"Los Guasimitos","municipality"=>"Obispos","state"=>"Barinas"],
			["name"=>"Sabaneta","municipality"=>"Alberto Arvelo Torrealba","state"=>"Barinas"],
			["name"=>"Rodriguez Dominguez","municipality"=>"Alberto Arvelo Torrealba","state"=>"Barinas"],
			["name"=>"Barinitas","municipality"=>"Bolivar","state"=>"Barinas"],
			["name"=>"Altamira","municipality"=>"Bolivar","state"=>"Barinas"],
			["name"=>"Calderas","municipality"=>"Bolivar","state"=>"Barinas"],
			["name"=>"Seccion Capital Gran Sabana","municipality"=>"Gran Sabana","state"=>"Bolivar"],
			["name"=>"Ikabaru","municipality"=>"Gran Sabana","state"=>"Bolivar"],
			["name"=>"Agua Salada","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Catedral","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Jose Antonio Paez","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"La Sabanita","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Marhuanta","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Vista Hermosa","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Orinoco","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Panapana","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Zea","municipality"=>"Heres","state"=>"Bolivar"],
			["name"=>"Seccion Capital Sucre","municipality"=>"Sucre","state"=>"Bolivar"],
			["name"=>"Aripao","municipality"=>"Sucre","state"=>"Bolivar"],
			["name"=>"Guarataro","municipality"=>"Sucre","state"=>"Bolivar"],
			["name"=>"Las Majadas","municipality"=>"Sucre","state"=>"Bolivar"],
			["name"=>"Moitaco","municipality"=>"Sucre","state"=>"Bolivar"],
			["name"=>"No Tiene Parroquia (Capital El Palmar)","municipality"=>"Padre Pedro Chien","state"=>"Bolivar"],
			["name"=>"Seccion Capital Piar","municipality"=>"Piar","state"=>"Bolivar"],
			["name"=>"Andre Eloy Blanco","municipality"=>"Piar","state"=>"Bolivar"],
			["name"=>"Pedro Cova","municipality"=>"Piar","state"=>"Bolivar"],
			["name"=>"Seccion Capital Cedeno","municipality"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"Altagracia","municipality"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"Ascension Farreras","municipality"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"Guaniamo","municipality"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"La Urbana","municipality"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"Pijiguaos","municipality"=>"Cedeño","state"=>"Bolivar"],
			["name"=>"Seccion Capital Sifontes","municipality"=>"Sifontes","state"=>"Bolivar"],
			["name"=>"Dalla Costa","municipality"=>"Sifontes","state"=>"Bolivar"],
			["name"=>"San Isidro","municipality"=>"Sifontes","state"=>"Bolivar"],
			["name"=>"Seccion Capital Roscio","municipality"=>"Roscio","state"=>"Bolivar"],
			["name"=>"Salom","municipality"=>"Roscio","state"=>"Bolivar"],
			["name"=>"No Tiene Parroquia (Capital El Callao)","municipality"=>"El Callao","state"=>"Bolivar"],
			["name"=>"Cachamay","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Chirica","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Dalla Costa","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Once De Abril","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Simon Bolivar","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Unare","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Universidad","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Vista Al Sol","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Pozo Verde","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Yocoima","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Cinco De Julio","municipality"=>"Caroni","state"=>"Bolivar"],
			["name"=>"Seccion Capital Angostura","municipality"=>"Bolivariano Angostura","state"=>"Bolivar"],
			["name"=>"Barceloneta","municipality"=>"Bolivariano Angostura","state"=>"Bolivar"],
			["name"=>"San Francisco","municipality"=>"Bolivariano Angostura","state"=>"Bolivar"],
			["name"=>"Santa Barbara","municipality"=>"Bolivariano Angostura","state"=>"Bolivar"],
			["name"=>"Urbana Miranda","municipality"=>"Miranda","state"=>"Carabobo"],
			["name"=>"Urbana Bejuma","municipality"=>"Bejuma","state"=>"Carabobo"],
			["name"=>"No Urbana Canoabo","municipality"=>"Bejuma","state"=>"Carabobo"],
			["name"=>"No Urbana Simon Bolivar","municipality"=>"Bejuma","state"=>"Carabobo"],
			["name"=>"Urbana San Diego","municipality"=>"San Diego","state"=>"Carabobo"],
			["name"=>"Urbana Aguas Calientes","municipality"=>"Diego Ibarra","state"=>"Carabobo"],
			["name"=>"Urbana Mariara","municipality"=>"Diego Ibarra","state"=>"Carabobo"],
			["name"=>"Urbana Moron","municipality"=>"Juan Jose Mora","state"=>"Carabobo"],
			["name"=>"No Urbana Urama","municipality"=>"Juan Jose Mora","state"=>"Carabobo"],
			["name"=>"Urbana Güigüe","municipality"=>"Carlos Arvelo","state"=>"Carabobo"],
			["name"=>"No Urbana Belen","municipality"=>"Carlos Arvelo","state"=>"Carabobo"],
			["name"=>"No Urbana Tacarigua","municipality"=>"Carlos Arvelo","state"=>"Carabobo"],
			["name"=>"Urbana Bartolome Salom","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Urbana Democracia","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Urbana Fraternidad","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Urbana Goaigoaza","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Urbana Juan Jose Flores","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Urbana Union","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"No Urbana Borburata","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"No Urbana Patanemo","municipality"=>"Puerto Cabello","state"=>"Carabobo"],
			["name"=>"Urbana Naguanagua","municipality"=>"Naguanagua","state"=>"Carabobo"],
			["name"=>"Urbana Candelaria","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana Catedral","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana El Socorro","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana Miguel Peña","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana Rafael Urdaneta","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana San Blas","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana San Jose","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana Santa Rosa","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"No Urbana Negro Primero","municipality"=>"Valencia","state"=>"Carabobo"],
			["name"=>"Urbana Tocuyito","municipality"=>"Libertador","state"=>"Carabobo"],
			["name"=>"Urbana Independencia","municipality"=>"Libertador","state"=>"Carabobo"],
			["name"=>"Urbana Los Guayos","municipality"=>"Los Guayos","state"=>"Carabobo"],
			["name"=>"Urbana Ciudad Alianza","municipality"=>"Guacara","state"=>"Carabobo"],
			["name"=>"Urbana Guacara","municipality"=>"Guacara","state"=>"Carabobo"],
			["name"=>"No Urbana Yagua","municipality"=>"Guacara","state"=>"Carabobo"],
			["name"=>"Urbana Montalban","municipality"=>"Montalban","state"=>"Carabobo"],
			["name"=>"Urbana San Joaquin","municipality"=>"San Joaquin","state"=>"Carabobo"],
			["name"=>"El Pao","municipality"=>"Pao De San Juan Bautista","state"=>"Cojedes"],
			["name"=>"Romulo Gallegos","municipality"=>"Romulo Gallegos","state"=>"Cojedes"],
			["name"=>"San Carlos De Austria","municipality"=>"Ezequiel Zamora","state"=>"Cojedes"],
			["name"=>"Juan ├Üngel Bravo","municipality"=>"Ezequiel Zamora","state"=>"Cojedes"],
			["name"=>"Manuel Manrique","municipality"=>"Ezequiel Zamora","state"=>"Cojedes"],
			["name"=>"Libertad De Cojedes","municipality"=>"Ricaurte","state"=>"Cojedes"],
			["name"=>"El Amparo","municipality"=>"Ricaurte","state"=>"Cojedes"],
			["name"=>"General En Jefe Jose Laurencio Silva","municipality"=>"Tinaco","state"=>"Cojedes"],
			["name"=>"Macapo","municipality"=>"Lima Blanco","state"=>"Cojedes"],
			["name"=>"La Aguadita","municipality"=>"Lima Blanco","state"=>"Cojedes"],
			["name"=>"Tinaquillo","municipality"=>"Tinaquillo","state"=>"Cojedes"],
			["name"=>"Cojedes","municipality"=>"Anzoategui","state"=>"Cojedes"],
			["name"=>"Juan De Mata Suarez","municipality"=>"Anzoategui","state"=>"Cojedes"],
			["name"=>"El Baul","municipality"=>"Girardot","state"=>"Cojedes"],
			["name"=>"Sucre","municipality"=>"Girardot","state"=>"Cojedes"],
			["name"=>"Imataca","municipality"=>"Casacoima","state"=>"Delta Amacuro"],
			["name"=>"Juan Bautista Arismendi","municipality"=>"Casacoima","state"=>"Delta Amacuro"],
			["name"=>"Manuel Piar","municipality"=>"Casacoima","state"=>"Delta Amacuro"],
			["name"=>"Romulo Gallegos","municipality"=>"Casacoima","state"=>"Delta Amacuro"],
			["name"=>"Pedernales","municipality"=>"Pedernales","state"=>"Delta Amacuro"],
			["name"=>"Luis Beltran Prieto Figueroa","municipality"=>"Pedernales","state"=>"Delta Amacuro"],
			["name"=>"San Jose","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Jose Vidal Marcano","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Juan Millan","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Leonardo Ruiz Pineda","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Mariscal Antonio Jose De Sucre","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Monseñor Argimiro Garcia","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"San Rafael","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Virgen Del Valle","municipality"=>"Tucupita","state"=>"Delta Amacuro"],
			["name"=>"Curiapo","municipality"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"Almirante Luis Brion","municipality"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"Francisco Aniceto Lugo","municipality"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"Manuel Renaud","municipality"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"Padre Barral","municipality"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"Santos De Abelgas","municipality"=>"Antonio Diaz","state"=>"Delta Amacuro"],
			["name"=>"No Tiene Parroquia (Capital Dabajuro)","municipality"=>"Dabajuro","state"=>"Falcon"],
			["name"=>"Pedregal","municipality"=>"Democracia","state"=>"Falcon"],
			["name"=>"Agua Clara","municipality"=>"Democracia","state"=>"Falcon"],
			["name"=>"Avaria","municipality"=>"Democracia","state"=>"Falcon"],
			["name"=>"Piedra Grande","municipality"=>"Democracia","state"=>"Falcon"],
			["name"=>"Purureche","municipality"=>"Democracia","state"=>"Falcon"],
			["name"=>"Pueblo Nuevo","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Adicora","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Baraived","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Buena Vista","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Jadacaquiva","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Moruy","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Adaure","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"El Hato","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"El Vinculo","municipality"=>"Falcon","state"=>"Falcon"],
			["name"=>"Carirubana","municipality"=>"Carirubana","state"=>"Falcon"],
			["name"=>"Norte","municipality"=>"Carirubana","state"=>"Falcon"],
			["name"=>"Punta Cardon","municipality"=>"Carirubana","state"=>"Falcon"],
			["name"=>"Santa Ana","municipality"=>"Carirubana","state"=>"Falcon"],
			["name"=>"La Vela De Coro","municipality"=>"Colina","state"=>"Falcon"],
			["name"=>"Acurigua","municipality"=>"Colina","state"=>"Falcon"],
			["name"=>"Guaibacoa","municipality"=>"Colina","state"=>"Falcon"],
			["name"=>"Las Calderas","municipality"=>"Colina","state"=>"Falcon"],
			["name"=>"Macoruca","municipality"=>"Colina","state"=>"Falcon"],
			["name"=>"Churuguara","municipality"=>"Federacion","state"=>"Falcon"],
			["name"=>"Agua Larga","municipality"=>"Federacion","state"=>"Falcon"],
			["name"=>"El Pauji","municipality"=>"Federacion","state"=>"Falcon"],
			["name"=>"Independencia","municipality"=>"Federacion","state"=>"Falcon"],
			["name"=>"Maparari","municipality"=>"Federacion","state"=>"Falcon"],
			["name"=>"Mene De Mauroa","municipality"=>"Mauroa","state"=>"Falcon"],
			["name"=>"Casigua","municipality"=>"Mauroa","state"=>"Falcon"],
			["name"=>"San Felix","municipality"=>"Mauroa","state"=>"Falcon"],
			["name"=>"San Juan De Los Cayos","municipality"=>"Acosta","state"=>"Falcon"],
			["name"=>"Capadare","municipality"=>"Acosta","state"=>"Falcon"],
			["name"=>"La Pastora","municipality"=>"Acosta","state"=>"Falcon"],
			["name"=>"Libertador","municipality"=>"Acosta","state"=>"Falcon"],
			["name"=>"San Antonio","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"San Gabriel","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"Santa Ana","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"Guzman Guillermo","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"Mitare","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"Rio Seco","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"Sabaneta","municipality"=>"Miranda","state"=>"Falcon"],
			["name"=>"Chichiriviche","municipality"=>"Monseñor Iturriza","state"=>"Falcon"],
			["name"=>"Boca De Tocuyo","municipality"=>"Monseñor Iturriza","state"=>"Falcon"],
			["name"=>"Tocuyo De La Costa","municipality"=>"Monseñor Iturriza","state"=>"Falcon"],
			["name"=>"Piritu","municipality"=>"Piritu","state"=>"Falcon"],
			["name"=>"San Jose De La Costa","municipality"=>"Piritu","state"=>"Falcon"],
			["name"=>"No Tiene Parroquia (Capital Palmasola)","municipality"=>"Palmasola","state"=>"Falcon"],
			["name"=>"Tucacas","municipality"=>"Silva","state"=>"Falcon"],
			["name"=>"Boca De Aroa","municipality"=>"Silva","state"=>"Falcon"],
			["name"=>"Capatarida","municipality"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Bariro","municipality"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Borojo","municipality"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Guajiro","municipality"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Seque","municipality"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Zazarida","municipality"=>"Buchivacoa","state"=>"Falcon"],
			["name"=>"Jacura","municipality"=>"Jacura","state"=>"Falcon"],
			["name"=>"Agua Linda","municipality"=>"Jacura","state"=>"Falcon"],
			["name"=>"Araurima","municipality"=>"Jacura","state"=>"Falcon"],
			["name"=>"No Tiene Parroquia (Capital Mirimire)","municipality"=>"San Francisco","state"=>"Falcon"],
			["name"=>"No Tiene Parroquia (Capital Tocopero)","municipality"=>"Tocopero","state"=>"Falcon"],
			["name"=>"Urumaco","municipality"=>"Urumaco","state"=>"Falcon"],
			["name"=>"Bruzual","municipality"=>"Urumaco","state"=>"Falcon"],
			["name"=>"Puerto Cumarebo","municipality"=>"Zamora","state"=>"Falcon"],
			["name"=>"La Cienaga","municipality"=>"Zamora","state"=>"Falcon"],
			["name"=>"La Soledad","municipality"=>"Zamora","state"=>"Falcon"],
			["name"=>"Pueblo Cumarebo","municipality"=>"Zamora","state"=>"Falcon"],
			["name"=>"Zazarida","municipality"=>"Zamora","state"=>"Falcon"],
			["name"=>"Cabure","municipality"=>"Petit","state"=>"Falcon"],
			["name"=>"Colina","municipality"=>"Petit","state"=>"Falcon"],
			["name"=>"Curimagua","municipality"=>"Petit","state"=>"Falcon"],
			["name"=>"Sucre","municipality"=>"Sucre","state"=>"Falcon"],
			["name"=>"Pecaya","municipality"=>"Sucre","state"=>"Falcon"],
			["name"=>"Santa Cruz De Bucaral","municipality"=>"Union","state"=>"Falcon"],
			["name"=>"El Charal","municipality"=>"Union","state"=>"Falcon"],
			["name"=>"Las Vegas Del Tuy","municipality"=>"Union","state"=>"Falcon"],
			["name"=>"San Luis","municipality"=>"Bolivar","state"=>"Falcon"],
			["name"=>"Aracua","municipality"=>"Bolivar","state"=>"Falcon"],
			["name"=>"La Peña","municipality"=>"Bolivar","state"=>"Falcon"],
			["name"=>"No Tiene Parroquia (Capital Yaracal)","municipality"=>"Cacique Manuare","state"=>"Falcon"],
			["name"=>"Los Taques","municipality"=>"Los Taques","state"=>"Falcon"],
			["name"=>"Judibana","municipality"=>"Los Taques","state"=>"Falcon"],
			["name"=>"San Jose De Guaribe","municipality"=>"San Jose De Guaribe","state"=>"Guarico"],
			["name"=>"Capital Camaguan","municipality"=>"Camaguan","state"=>"Guarico"],
			["name"=>"Puerto Miranda","municipality"=>"Camaguan","state"=>"Guarico"],
			["name"=>"Uverito","municipality"=>"Camaguan","state"=>"Guarico"],
			["name"=>"Capital El Sombrero","municipality"=>"Julian Mellado","state"=>"Guarico"],
			["name"=>"Sosa","municipality"=>"Julian Mellado","state"=>"Guarico"],
			["name"=>"Capital Santa Maria De Ipire","municipality"=>"Santa Maria De Ipire","state"=>"Guarico"],
			["name"=>"Altamira","municipality"=>"Santa Maria De Ipire","state"=>"Guarico"],
			["name"=>"Chaguaramas","municipality"=>"Chaguaramas","state"=>"Guarico"],
			["name"=>"Capital San Geronimo De Guayabal","municipality"=>"San Geronimo De Guayabal","state"=>"Guarico"],
			["name"=>"Cazorla","municipality"=>"San Geronimo De Guayabal","state"=>"Guarico"],
			["name"=>"Capital San Juan De Los Morros","municipality"=>"Juan German Roscio","state"=>"Guarico"],
			["name"=>"Cantagallo","municipality"=>"Juan German Roscio","state"=>"Guarico"],
			["name"=>"Parapara","municipality"=>"Juan German Roscio","state"=>"Guarico"],
			["name"=>"Capital Tucupido","municipality"=>"Jose Felix Rivas","state"=>"Guarico"],
			["name"=>"San Rafael De Laya","municipality"=>"Jose Felix Rivas","state"=>"Guarico"],
			["name"=>"Capital Las Mercedes","municipality"=>"Las Mercedes","state"=>"Guarico"],
			["name"=>"Cabruta","municipality"=>"Las Mercedes","state"=>"Guarico"],
			["name"=>"Santa Rita De Manapire","municipality"=>"Las Mercedes","state"=>"Guarico"],
			["name"=>"Capital Zaraza","municipality"=>"Pedro Zaraza","state"=>"Guarico"],
			["name"=>"San Jose De Unare","municipality"=>"Pedro Zaraza","state"=>"Guarico"],
			["name"=>"Capital Ortiz","municipality"=>"Ortiz","state"=>"Guarico"],
			["name"=>"San Francisco De Tiznado","municipality"=>"Ortiz","state"=>"Guarico"],
			["name"=>"San Jose De Tiznado","municipality"=>"Ortiz","state"=>"Guarico"],
			["name"=>"San Lorenzo De Tiznado","municipality"=>"Ortiz","state"=>"Guarico"],
			["name"=>"Capital Altagracia De Orituco","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"Lezama","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"Libertad De Orituco","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"Paso Real De Macaira","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"San Francisco De Macaira","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"San Rafael De Orituco","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"Soublette","municipality"=>"Jose Tadeo Monagas","state"=>"Guarico"],
			["name"=>"Capital Valle De La Pascua","municipality"=>"Leonardo Infante","state"=>"Guarico"],
			["name"=>"Espino","municipality"=>"Leonardo Infante","state"=>"Guarico"],
			["name"=>"Capital Calabozo","municipality"=>"Francisco De Miranda","state"=>"Guarico"],
			["name"=>"El Calvario","municipality"=>"Francisco De Miranda","state"=>"Guarico"],
			["name"=>"El Rastro","municipality"=>"Francisco De Miranda","state"=>"Guarico"],
			["name"=>"Guardatinajas","municipality"=>"Francisco De Miranda","state"=>"Guarico"],
			["name"=>"El Socorro","municipality"=>"El Socorro","state"=>"Guarico"],
			["name"=>"Juan Bautista Rodriguez","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Cuara","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Diego De Lozada","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Paraiso De San Jose","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"San Miguel","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Tintorero","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Jose Bernardo Dorante","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Coronel Mariano Peraza","municipality"=>"Jimenez","state"=>"Lara"],
			["name"=>"Siquisique","municipality"=>"Urdaneta","state"=>"Lara"],
			["name"=>"Moroturo","municipality"=>"Urdaneta","state"=>"Lara"],
			["name"=>"San Miguel","municipality"=>"Urdaneta","state"=>"Lara"],
			["name"=>"Xaguas","municipality"=>"Urdaneta","state"=>"Lara"],
			["name"=>"Pio Tamayo","municipality"=>"Andre Eloy Blanco","state"=>"Lara"],
			["name"=>"Quebrada Honda De Guache","municipality"=>"Andre Eloy Blanco","state"=>"Lara"],
			["name"=>"Yacambu","municipality"=>"Andre Eloy Blanco","state"=>"Lara"],
			["name"=>"Sarare","municipality"=>"Simon Planas","state"=>"Lara"],
			["name"=>"Buria","municipality"=>"Simon Planas","state"=>"Lara"],
			["name"=>"Gustavo Vegas Leon","municipality"=>"Simon Planas","state"=>"Lara"],
			["name"=>"Catedral","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Concepcion","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"El Cuji","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Juan De Villegas","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Santa Rosa","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Tamaca","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Union","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Aguedo Felipe Alvarado","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Buena Vista","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Juarez","municipality"=>"Iribarren","state"=>"Lara"],
			["name"=>"Freitez","municipality"=>"Crespo","state"=>"Lara"],
			["name"=>"Jose Maria Blanco","municipality"=>"Crespo","state"=>"Lara"],
			["name"=>"Trinidad Samuel","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Antonio Diaz","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Camacaro","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Castañeda","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Cecilio Zubillaga","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Chiquinquira","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"El Blanco","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Espinoza De Los Monteros","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Lara","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Las Mercedes","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Manuel Morillo","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Montaña Verde","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Montes De Oca","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Torres","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Reyes Vargas","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Altagracia","municipality"=>"Torres","state"=>"Lara"],
			["name"=>"Bolivar","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Anzoategui","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Guarico","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Hilario Luna Y Luna","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Humocaro Alto","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Humocaro Bajo","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"La Candelaria","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Moran","municipality"=>"Moran","state"=>"Lara"],
			["name"=>"Cabudare","municipality"=>"Palavecino","state"=>"Lara"],
			["name"=>"Jose Gregorio Bastidas","municipality"=>"Palavecino","state"=>"Lara"],
			["name"=>"Agua Viva","municipality"=>"Palavecino","state"=>"Lara"],
			["name"=>"Capital Aricagua","municipality"=>"Aricagua","state"=>"Merida"],
			["name"=>"San Antonio","municipality"=>"Aricagua","state"=>"Merida"],
			["name"=>"Presidente Betancourt","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Presidente Paez","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Presidente Romulo Gallegos","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Gabriel Picon Gonzalez","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Hector Amable Mora","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Jose Nucete Sardi","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Pulido Mendez","municipality"=>"Alberto Adriani","state"=>"Merida"],
			["name"=>"Capital Caracciolo Parra Olmedo","municipality"=>"Caracciolo Parra Olmedo","state"=>"Merida"],
			["name"=>"Florencio Ramirez","municipality"=>"Caracciolo Parra Olmedo","state"=>"Merida"],
			["name"=>"Capital Antonio Pinto Salinas","municipality"=>"Antonio Pinto  Salinas","state"=>"Merida"],
			["name"=>"Mesa Bolivar","municipality"=>"Antonio Pinto  Salinas","state"=>"Merida"],
			["name"=>"Mesa De Las Palmas","municipality"=>"Antonio Pinto  Salinas","state"=>"Merida"],
			["name"=>"Capital Arzobispo Chacon","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Capuri","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Chacanta","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"El Molino","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Guaimaral","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Mucutuy","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Mucuchachi","municipality"=>"Arzobispo Chacon","state"=>"Merida"],
			["name"=>"Antonio Spinetti Dini","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Arias","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Caracciolo Parra Perez","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Domingo Peña","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"El Llano","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Gonzalo Picon Febres","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Jacinto Plaza","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Juan Rodriguez Suarez","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Lasso De La Vega","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Mariano Picon Salas","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Milla","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Osuna Rodriguez","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Sagrario","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"El Morro","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Los Nevados","municipality"=>"Libertador","state"=>"Merida"],
			["name"=>"Capital Obispo Ramos De Lora","municipality"=>"Obispo Ramos De Lora","state"=>"Merida"],
			["name"=>"Eloy Paredes","municipality"=>"Obispo Ramos De Lora","state"=>"Merida"],
			["name"=>"San Rafael De Alcazar","municipality"=>"Obispo Ramos De Lora","state"=>"Merida"],
			["name"=>"Capital Guaraque","municipality"=>"Guaraque","state"=>"Merida"],
			["name"=>"Mesa De Quintero","municipality"=>"Guaraque","state"=>"Merida"],
			["name"=>"Rio Negro","municipality"=>"Guaraque","state"=>"Merida"],
			["name"=>"No Tiene Parroquia (Capital Pueblo Llano)","municipality"=>"Pueblo Llano","state"=>"Merida"],
			["name"=>"Capital Rivas Davila","municipality"=>"Rivas Davila","state"=>"Merida"],
			["name"=>"Geronimo Maldonado","municipality"=>"Rivas Davila","state"=>"Merida"],
			["name"=>"Capital Zea","municipality"=>"Zea","state"=>"Merida"],
			["name"=>"Caño El Tigre","municipality"=>"Zea","state"=>"Merida"],
			["name"=>"Fernandez Pena","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"Matriz","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"Montalban","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"Acequias","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"Jaji","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"La Mesa","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"San Jose Del Sur","municipality"=>"Campo  Elias","state"=>"Merida"],
			["name"=>"Capital Miranda","municipality"=>"Miranda","state"=>"Merida"],
			["name"=>"Andre Eloy Blanco","municipality"=>"Miranda","state"=>"Merida"],
			["name"=>"La Venta","municipality"=>"Miranda","state"=>"Merida"],
			["name"=>"Piñango","municipality"=>"Miranda","state"=>"Merida"],
			["name"=>"Capital Justo Briceño","municipality"=>"Justo Briceño","state"=>"Merida"],
			["name"=>"San Cristobal De Torondoy","municipality"=>"Justo Briceño","state"=>"Merida"],
			["name"=>"El Amparo","municipality"=>"Tovar","state"=>"Merida"],
			["name"=>"El Llano","municipality"=>"Tovar","state"=>"Merida"],
			["name"=>"San Francisco","municipality"=>"Tovar","state"=>"Merida"],
			["name"=>"Tovar","municipality"=>"Tovar","state"=>"Merida"],
			["name"=>"Capital Tulio Febres Cordero","municipality"=>"Tulio Febres Cordero","state"=>"Merida"],
			["name"=>"Independencia","municipality"=>"Tulio Febres Cordero","state"=>"Merida"],
			["name"=>"Maria De La Concepcion Palacios Blanco","municipality"=>"Tulio Febres Cordero","state"=>"Merida"],
			["name"=>"Santa Apolonia","municipality"=>"Tulio Febres Cordero","state"=>"Merida"],
			["name"=>"No Tiene Parroquia (Capital Santa Maria De Caparo)","municipality"=>"Padre Noguera","state"=>"Merida"],
			["name"=>"Capital Sucre","municipality"=>"Sucre","state"=>"Merida"],
			["name"=>"Chiguara","municipality"=>"Sucre","state"=>"Merida"],
			["name"=>"Estanques","municipality"=>"Sucre","state"=>"Merida"],
			["name"=>"La Trampa","municipality"=>"Sucre","state"=>"Merida"],
			["name"=>"Pueblo Nuevo Del Sur","municipality"=>"Sucre","state"=>"Merida"],
			["name"=>"San Juan","municipality"=>"Sucre","state"=>"Merida"],
			["name"=>"No Tiene Parroquia (Capital Tabay)","municipality"=>"Santos Marquina","state"=>"Merida"],
			["name"=>"Capital Cardenal Quintero","municipality"=>"Cardenal Quintero","state"=>"Merida"],
			["name"=>"Las Piedras","municipality"=>"Cardenal Quintero","state"=>"Merida"],
			["name"=>"No Tiene Parroquia (Capital La Azulita)","municipality"=>"Andre Bello","state"=>"Merida"],
			["name"=>"Capital Julio Cear Salas","municipality"=>"Julio Cear Salas","state"=>"Merida"],
			["name"=>"Palmira","municipality"=>"Julio Cear Salas","state"=>"Merida"],
			["name"=>"Capital Rangel","municipality"=>"Rangel","state"=>"Merida"],
			["name"=>"Cacute","municipality"=>"Rangel","state"=>"Merida"],
			["name"=>"La Toma","municipality"=>"Rangel","state"=>"Merida"],
			["name"=>"Mucuruba","municipality"=>"Rangel","state"=>"Merida"],
			["name"=>"San Rafael","municipality"=>"Rangel","state"=>"Merida"],
			["name"=>"Baruta","municipality"=>"Baruta","state"=>"Bolivariano De Miranda"],
			["name"=>"El Cafetal","municipality"=>"Baruta","state"=>"Bolivariano De Miranda"],
			["name"=>"Las Minas De Baruta","municipality"=>"Baruta","state"=>"Bolivariano De Miranda"],
			["name"=>"Carrizal","municipality"=>"Carrizal","state"=>"Bolivariano De Miranda"],
			["name"=>"Ocumare Del Tuy","municipality"=>"Lander","state"=>"Bolivariano De Miranda"],
			["name"=>"La Democracia","municipality"=>"Lander","state"=>"Bolivariano De Miranda"],
			["name"=>"Santa Barbara","municipality"=>"Lander","state"=>"Bolivariano De Miranda"],
			["name"=>"El Hatillo","municipality"=>"El Hatillo","state"=>"Bolivariano De Miranda"],
			["name"=>"San Antonio De Los Altos","municipality"=>"Los Salias","state"=>"Bolivariano De Miranda"],
			["name"=>"Mamporal","municipality"=>"Buroz","state"=>"Bolivariano De Miranda"],
			["name"=>"Guatire","municipality"=>"Zamora","state"=>"Bolivariano De Miranda"],
			["name"=>"Bolivar","municipality"=>"Zamora","state"=>"Bolivariano De Miranda"],
			["name"=>"Cupira","municipality"=>"Pedro  Gual","state"=>"Bolivariano De Miranda"],
			["name"=>"Machurucuto","municipality"=>"Pedro  Gual","state"=>"Bolivariano De Miranda"],
			["name"=>"Charallave","municipality"=>"Cristobal Rojas","state"=>"Bolivariano De Miranda"],
			["name"=>"Las Brisas","municipality"=>"Cristobal Rojas","state"=>"Bolivariano De Miranda"],
			["name"=>"Cua","municipality"=>"Urdaneta","state"=>"Bolivariano De Miranda"],
			["name"=>"Nueva Cua","municipality"=>"Urdaneta","state"=>"Bolivariano De Miranda"],
			["name"=>"San Jose De Barlovento","municipality"=>"Andre Bello","state"=>"Bolivariano De Miranda"],
			["name"=>"Cumbo","municipality"=>"Andre Bello","state"=>"Bolivariano De Miranda"],
			["name"=>"Caucagua","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Aragüita","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Arevalo Gonzalez","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Capaya","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"El Cafe","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Marizapa","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Panaquire","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Ribas","municipality"=>"Acevedo","state"=>"Bolivariano De Miranda"],
			["name"=>"Higuerote","municipality"=>"Brion","state"=>"Bolivariano De Miranda"],
			["name"=>"Curiepe","municipality"=>"Brion","state"=>"Bolivariano De Miranda"],
			["name"=>"Tacarigua","municipality"=>"Brion","state"=>"Bolivariano De Miranda"],
			["name"=>"Chacao","municipality"=>"Chacao","state"=>"Bolivariano De Miranda"],
			["name"=>"Guarenas","municipality"=>"Plaza","state"=>"Bolivariano De Miranda"],
			["name"=>"Santa Lucia","municipality"=>"Paz Castillo","state"=>"Bolivariano De Miranda"],
			["name"=>"Santa Teresa Del Tuy","municipality"=>"Independencia","state"=>"Bolivariano De Miranda"],
			["name"=>"El Cartanal","municipality"=>"Independencia","state"=>"Bolivariano De Miranda"],
			["name"=>"Los Teques","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"Altagracia De La Montaña","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"Cecilio Acosta","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"El Jarillo","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"Paracotos","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"San Pedro","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"Tacata","municipality"=>"Bolivariano Guaicaipuro","state"=>"Bolivariano De Miranda"],
			["name"=>"Rio Chico","municipality"=>"Paez","state"=>"Bolivariano De Miranda"],
			["name"=>"El Guapo","municipality"=>"Paez","state"=>"Bolivariano De Miranda"],
			["name"=>"Tacarigua De La Laguna","municipality"=>"Paez","state"=>"Bolivariano De Miranda"],
			["name"=>"Paparo","municipality"=>"Paez","state"=>"Bolivariano De Miranda"],
			["name"=>"San Fernando Del Guapo","municipality"=>"Paez","state"=>"Bolivariano De Miranda"],
			["name"=>"San Francisco De Yare","municipality"=>"Simon Bolivar","state"=>"Bolivariano De Miranda"],
			["name"=>"San Antonio De Yare","municipality"=>"Simon Bolivar","state"=>"Bolivariano De Miranda"],
			["name"=>"Petare","municipality"=>"Sucre","state"=>"Bolivariano De Miranda"],
			["name"=>"Caucagüita","municipality"=>"Sucre","state"=>"Bolivariano De Miranda"],
			["name"=>"Fila De Mariches","municipality"=>"Sucre","state"=>"Bolivariano De Miranda"],
			["name"=>"La Dolorita","municipality"=>"Sucre","state"=>"Bolivariano De Miranda"],
			["name"=>"Leoncio Martinez","municipality"=>"Sucre","state"=>"Bolivariano De Miranda"],
			["name"=>"No Tiene Parroquia (Capital Aguasay)","municipality"=>"Aguasay","state"=>"Monagas"],
			["name"=>"Capital Caripe","municipality"=>"Caripe","state"=>"Monagas"],
			["name"=>"El Guacharo","municipality"=>"Caripe","state"=>"Monagas"],
			["name"=>"La Guanota","municipality"=>"Caripe","state"=>"Monagas"],
			["name"=>"Sabana De Piedra","municipality"=>"Caripe","state"=>"Monagas"],
			["name"=>"San Agustin","municipality"=>"Caripe","state"=>"Monagas"],
			["name"=>"Teresen","municipality"=>"Caripe","state"=>"Monagas"],
			["name"=>"Capital Ezequiel Zamora","municipality"=>"Ezequiel Zamora","state"=>"Monagas"],
			["name"=>"El Tejero","municipality"=>"Ezequiel Zamora","state"=>"Monagas"],
			["name"=>"Capital Maturin","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"Alto De Los Godos","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"Boqueron","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"Las Cocuizas","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"San Simon","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"Santa Cruz","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"El Corozo","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"El Furrial","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"Jusepin","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"La Pica","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"San Vicente","municipality"=>"Maturin","state"=>"Monagas"],
			["name"=>"Capital Libertador","municipality"=>"Libertador","state"=>"Monagas"],
			["name"=>"Chaguaramas","municipality"=>"Libertador","state"=>"Monagas"],
			["name"=>"Las Alhuacas","municipality"=>"Libertador","state"=>"Monagas"],
			["name"=>"Tabasca","municipality"=>"Libertador","state"=>"Monagas"],
			["name"=>"No Tiene Parroquia (Capital Santa Barbara)","municipality"=>"Santa Barbara","state"=>"Monagas"],
			["name"=>"Capital Sotillo","municipality"=>"Sotillo","state"=>"Monagas"],
			["name"=>"Los Barrancos De Fajardo","municipality"=>"Sotillo","state"=>"Monagas"],
			["name"=>"Capital Cedeño","municipality"=>"Cedeño","state"=>"Monagas"],
			["name"=>"Areo","municipality"=>"Cedeño","state"=>"Monagas"],
			["name"=>"San Felix","municipality"=>"Cedeño","state"=>"Monagas"],
			["name"=>"Viento Fresco","municipality"=>"Cedeño","state"=>"Monagas"],
			["name"=>"No Tiene Parroquia (Capital Caripito)","municipality"=>"Bolivar","state"=>"Monagas"],
			["name"=>"Capital Piar","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"Aparicio","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"Chaguaramal","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"El Pinto","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"Guanaguana","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"La Toscana","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"Taguaya","municipality"=>"Piar","state"=>"Monagas"],
			["name"=>"No Tiene Parroquia (Capital Uracoa)","municipality"=>"Uracoa","state"=>"Monagas"],
			["name"=>"Capital Acosta","municipality"=>"Acosta","state"=>"Monagas"],
			["name"=>"San Francisco","municipality"=>"Acosta","state"=>"Monagas"],
			["name"=>"Capital Punceres","municipality"=>"Punceres","state"=>"Monagas"],
			["name"=>"Cachipo","municipality"=>"Punceres","state"=>"Monagas"],
			["name"=>"No Tiene Parroquia (Capital La Asuncion)","municipality"=>"Arismendi","state"=>"Nueva Esparta"],
			["name"=>"Capital Gomez","municipality"=>"Gomez","state"=>"Nueva Esparta"],
			["name"=>"Bolivar","municipality"=>"Gomez","state"=>"Nueva Esparta"],
			["name"=>"Guevara","municipality"=>"Gomez","state"=>"Nueva Esparta"],
			["name"=>"Matasiete","municipality"=>"Gomez","state"=>"Nueva Esparta"],
			["name"=>"Sucre","municipality"=>"Gomez","state"=>"Nueva Esparta"],
			["name"=>"Capital Marcano","municipality"=>"Marcano","state"=>"Nueva Esparta"],
			["name"=>"Adrian","municipality"=>"Marcano","state"=>"Nueva Esparta"],
			["name"=>"Capital Garcia","municipality"=>"Garcia","state"=>"Nueva Esparta"],
			["name"=>"Francisco Fajardo","municipality"=>"Garcia","state"=>"Nueva Esparta"],
			["name"=>"Capital Diaz","municipality"=>"Diaz","state"=>"Nueva Esparta"],
			["name"=>"Zabala","municipality"=>"Diaz","state"=>"Nueva Esparta"],
			["name"=>"Capital Tubores","municipality"=>"Tubores","state"=>"Nueva Esparta"],
			["name"=>"Los Barales","municipality"=>"Tubores","state"=>"Nueva Esparta"],
			["name"=>"Capital Maneiro","municipality"=>"Maneiro","state"=>"Nueva Esparta"],
			["name"=>"Aguirre","municipality"=>"Maneiro","state"=>"Nueva Esparta"],
			["name"=>"Capital Villalba","municipality"=>"Villalba","state"=>"Nueva Esparta"],
			["name"=>"Vicente Fuentes","municipality"=>"Villalba","state"=>"Nueva Esparta"],
			["name"=>"No Tiene Parroquia (Capital La Plaza De Paraguachi)","municipality"=>"Antolin Del Campo","state"=>"Nueva Esparta"],
			["name"=>"No Tiene Parroquia (Capital Porlamar)","municipality"=>"Mariño","state"=>"Nueva Esparta"],
			["name"=>"Capital Peninsula De Macanao","municipality"=>"Peninsula De Macanao","state"=>"Nueva Esparta"],
			["name"=>"San Francisco","municipality"=>"Peninsula De Macanao","state"=>"Nueva Esparta"],
			["name"=>"Capital Araure","municipality"=>"Araure","state"=>"Portuguesa"],
			["name"=>"Rio Acarigua","municipality"=>"Araure","state"=>"Portuguesa"],
			["name"=>"Capital Santa Rosalia","municipality"=>"Santa  Rosalia","state"=>"Portuguesa"],
			["name"=>"Florida","municipality"=>"Santa  Rosalia","state"=>"Portuguesa"],
			["name"=>"Capital Guanarito","municipality"=>"Guanarito","state"=>"Portuguesa"],
			["name"=>"Trinidad De La Capilla","municipality"=>"Guanarito","state"=>"Portuguesa"],
			["name"=>"Divina Pastora","municipality"=>"Guanarito","state"=>"Portuguesa"],
			["name"=>"Capital Guanare","municipality"=>"Guanare","state"=>"Portuguesa"],
			["name"=>"Cordoba","municipality"=>"Guanare","state"=>"Portuguesa"],
			["name"=>"San Jose De La Montaña","municipality"=>"Guanare","state"=>"Portuguesa"],
			["name"=>"San Juan De Guanaguanare","municipality"=>"Guanare","state"=>"Portuguesa"],
			["name"=>"Virgen De La Coromoto","municipality"=>"Guanare","state"=>"Portuguesa"],
			["name"=>"Capital San Genaro De Boconoito","municipality"=>"San Genaro De Boconoito","state"=>"Portuguesa"],
			["name"=>"Antolin Tovar","municipality"=>"San Genaro De Boconoito","state"=>"Portuguesa"],
			["name"=>"Capital San Rafael De Onoto","municipality"=>"San Rafael De Onoto","state"=>"Portuguesa"],
			["name"=>"Santa Fe","municipality"=>"San Rafael De Onoto","state"=>"Portuguesa"],
			["name"=>"Thermo Morles","municipality"=>"San Rafael De Onoto","state"=>"Portuguesa"],
			["name"=>"Capital Monseñor Jose Vicente De Unda","municipality"=>"Monseñor Jose Vicente De Unda","state"=>"Portuguesa"],
			["name"=>"Peña Blanca","municipality"=>"Monseñor Jose Vicente De Unda","state"=>"Portuguesa"],
			["name"=>"Capital Sucre","municipality"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"Concepcion","municipality"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"San Rafael De Palo Alzado","municipality"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"Uvencio Antonio Velasquez","municipality"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"San Jose De Saguaz","municipality"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"Villa Rosa","municipality"=>"Sucre","state"=>"Portuguesa"],
			["name"=>"Capital Papelon","municipality"=>"Papelon","state"=>"Portuguesa"],
			["name"=>"Caño Delgadito","municipality"=>"Papelon","state"=>"Portuguesa"],
			["name"=>"No Tiene Parroquia (Capital Agua Blanca)","municipality"=>"Agua Blanca","state"=>"Portuguesa"],
			["name"=>"Capital Esteller","municipality"=>"Esteller","state"=>"Portuguesa"],
			["name"=>"Uveral","municipality"=>"Esteller","state"=>"Portuguesa"],
			["name"=>"Capital Turen","municipality"=>"Turen","state"=>"Portuguesa"],
			["name"=>"Canelones","municipality"=>"Turen","state"=>"Portuguesa"],
			["name"=>"Santa Cruz","municipality"=>"Turen","state"=>"Portuguesa"],
			["name"=>"San Isidro Labrador","municipality"=>"Turen","state"=>"Portuguesa"],
			["name"=>"Capital Paez","municipality"=>"Paez","state"=>"Portuguesa"],
			["name"=>"Payara","municipality"=>"Paez","state"=>"Portuguesa"],
			["name"=>"Pimpinela","municipality"=>"Paez","state"=>"Portuguesa"],
			["name"=>"Ramon Peraza","municipality"=>"Paez","state"=>"Portuguesa"],
			["name"=>"Capital Ospino","municipality"=>"Ospino","state"=>"Portuguesa"],
			["name"=>"Aparicion","municipality"=>"Ospino","state"=>"Portuguesa"],
			["name"=>"La Estacion","municipality"=>"Ospino","state"=>"Portuguesa"],
			["name"=>"Mariño","municipality"=>"Andre Eloy Blanco","state"=>"Sucre"],
			["name"=>"Romulo Gallegos","municipality"=>"Andre Eloy Blanco","state"=>"Sucre"],
			["name"=>"Cumanacoa","municipality"=>"Montes","state"=>"Sucre"],
			["name"=>"Arenas","municipality"=>"Montes","state"=>"Sucre"],
			["name"=>"Aricagua","municipality"=>"Montes","state"=>"Sucre"],
			["name"=>"Cocollar","municipality"=>"Montes","state"=>"Sucre"],
			["name"=>"San Fernando","municipality"=>"Montes","state"=>"Sucre"],
			["name"=>"San Lorenzo","municipality"=>"Montes","state"=>"Sucre"],
			["name"=>"Bolivar","municipality"=>"Bermudez","state"=>"Sucre"],
			["name"=>"Macarapana","municipality"=>"Bermudez","state"=>"Sucre"],
			["name"=>"Santa Catalina","municipality"=>"Bermudez","state"=>"Sucre"],
			["name"=>"Santa Rosa","municipality"=>"Bermudez","state"=>"Sucre"],
			["name"=>"Santa Teresa","municipality"=>"Bermudez","state"=>"Sucre"],
			["name"=>"San Jose De Aerocuar","municipality"=>"Andre Mata","state"=>"Sucre"],
			["name"=>"Tavera Acosta","municipality"=>"Andre Mata","state"=>"Sucre"],
			["name"=>"El Pilar","municipality"=>"Benitez","state"=>"Sucre"],
			["name"=>"El Rincon","municipality"=>"Benitez","state"=>"Sucre"],
			["name"=>"General Francisco Antonio Vasquez","municipality"=>"Benitez","state"=>"Sucre"],
			["name"=>"Guara├║Nos","municipality"=>"Benitez","state"=>"Sucre"],
			["name"=>"Tunapuicito","municipality"=>"Benitez","state"=>"Sucre"],
			["name"=>"Union","municipality"=>"Benitez","state"=>"Sucre"],
			["name"=>"Irapa","municipality"=>"Mariño","state"=>"Sucre"],
			["name"=>"Campo Claro","municipality"=>"Mariño","state"=>"Sucre"],
			["name"=>"Marabal","municipality"=>"Mariño","state"=>"Sucre"],
			["name"=>"San Antonio De Irapa","municipality"=>"Mariño","state"=>"Sucre"],
			["name"=>"Soro","municipality"=>"Mariño","state"=>"Sucre"],
			["name"=>"No Tiene Parroquia (Capital San Antonio Del Golfo)","municipality"=>"Mejia","state"=>"Sucre"],
			["name"=>"Cariaco","municipality"=>"Ribero","state"=>"Sucre"],
			["name"=>"Catuaro","municipality"=>"Ribero","state"=>"Sucre"],
			["name"=>"Rendon","municipality"=>"Ribero","state"=>"Sucre"],
			["name"=>"Santa Cruz","municipality"=>"Ribero","state"=>"Sucre"],
			["name"=>"Santa Maria","municipality"=>"Ribero","state"=>"Sucre"],
			["name"=>"Tunapuy","municipality"=>"Libertador","state"=>"Sucre"],
			["name"=>"Campo Elias","municipality"=>"Libertador","state"=>"Sucre"],
			["name"=>"No Tiene Parroquia (Capital Marig├╝Itar)","municipality"=>"Bolivar","state"=>"Sucre"],
			["name"=>"Altagracia","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"Ayacucho","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"Santa Ine","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"Valentin Valiente","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"San Juan","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"Raul Leoni","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"Gran Mariscal","municipality"=>"Sucre","state"=>"Sucre"],
			["name"=>"Rio Caribe","municipality"=>"Arismendi","state"=>"Sucre"],
			["name"=>"Antonio Jose De Sucre","municipality"=>"Arismendi","state"=>"Sucre"],
			["name"=>"El Morro De Puerto Santo","municipality"=>"Arismendi","state"=>"Sucre"],
			["name"=>"Puerto Santo","municipality"=>"Arismendi","state"=>"Sucre"],
			["name"=>"San Juan De Las Galdonas","municipality"=>"Arismendi","state"=>"Sucre"],
			["name"=>"Araya","municipality"=>"Cruz Salmeron Acosta","state"=>"Sucre"],
			["name"=>"Chacopata","municipality"=>"Cruz Salmeron Acosta","state"=>"Sucre"],
			["name"=>"Manicuare","municipality"=>"Cruz Salmeron Acosta","state"=>"Sucre"],
			["name"=>"G├╝Iria","municipality"=>"Valdez","state"=>"Sucre"],
			["name"=>"Bideau","municipality"=>"Valdez","state"=>"Sucre"],
			["name"=>"Cristobal Colon","municipality"=>"Valdez","state"=>"Sucre"],
			["name"=>"Punta De Piedras","municipality"=>"Valdez","state"=>"Sucre"],
			["name"=>"Yaguaraparo","municipality"=>"Cajigal","state"=>"Sucre"],
			["name"=>"El Paujil","municipality"=>"Cajigal","state"=>"Sucre"],
			["name"=>"Libertad","municipality"=>"Cajigal","state"=>"Sucre"],
			["name"=>"Libertador","municipality"=>"Libertador","state"=>"Tachira"],
			["name"=>"Don Emeterio Ochoa","municipality"=>"Libertador","state"=>"Tachira"],
			["name"=>"Doradas","municipality"=>"Libertador","state"=>"Tachira"],
			["name"=>"San Joaquin De Navay","municipality"=>"Libertador","state"=>"Tachira"],
			["name"=>"Libertad","municipality"=>"Libertad","state"=>"Tachira"],
			["name"=>"Cipriano Castro","municipality"=>"Libertad","state"=>"Tachira"],
			["name"=>"Manuel Felipe Rugeles","municipality"=>"Libertad","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Santa Ana)","municipality"=>"Cordoba","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Michelena)","municipality"=>"Michelena","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Delicias)","municipality"=>"Rafael Urdaneta","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Las Mesas)","municipality"=>"Antonio Romulo Costa","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital San Simon)","municipality"=>"Simon Rodriguez","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Umuquena)","municipality"=>"San Judas Tadeo","state"=>"Tachira"],
			["name"=>"Cardenas","municipality"=>"Cardenas","state"=>"Tachira"],
			["name"=>"Amenodoro Rangel Lamus","municipality"=>"Cardenas","state"=>"Tachira"],
			["name"=>"La Florida","municipality"=>"Cardenas","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital El Cobre)","municipality"=>"Jose Maria Vargas","state"=>"Tachira"],
			["name"=>"Sucre","municipality"=>"Sucre","state"=>"Tachira"],
			["name"=>"Eleazar Lopez Contreras","municipality"=>"Sucre","state"=>"Tachira"],
			["name"=>"San Pablo","municipality"=>"Sucre","state"=>"Tachira"],
			["name"=>"Bolivar","municipality"=>"Bolivar","state"=>"Tachira"],
			["name"=>"Palotal","municipality"=>"Bolivar","state"=>"Tachira"],
			["name"=>"Juan Vicente Gomez","municipality"=>"Bolivar","state"=>"Tachira"],
			["name"=>"Isaias Medina Angarita","municipality"=>"Bolivar","state"=>"Tachira"],
			["name"=>"Panamericano","municipality"=>"Panamericano","state"=>"Tachira"],
			["name"=>"La Palmita","municipality"=>"Panamericano","state"=>"Tachira"],
			["name"=>"Ayacucho","municipality"=>"Ayacucho","state"=>"Tachira"],
			["name"=>"Rivas Berti","municipality"=>"Ayacucho","state"=>"Tachira"],
			["name"=>"San Pedro Del Rio","municipality"=>"Ayacucho","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Palmira)","municipality"=>"Guasimos","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Cordero)","municipality"=>"Andre Bello","state"=>"Tachira"],
			["name"=>"Fernandez Feo","municipality"=>"Fernandez Feo","state"=>"Tachira"],
			["name"=>"Alberto Adriani","municipality"=>"Fernandez Feo","state"=>"Tachira"],
			["name"=>"Santo Domingo","municipality"=>"Fernandez Feo","state"=>"Tachira"],
			["name"=>"Jauregui","municipality"=>"Jauregui","state"=>"Tachira"],
			["name"=>"Emilio Constantino Guerrero","municipality"=>"Jauregui","state"=>"Tachira"],
			["name"=>"Monseñor Miguel Antonio Salas","municipality"=>"Jauregui","state"=>"Tachira"],
			["name"=>"Junin","municipality"=>"Junin","state"=>"Tachira"],
			["name"=>"La Petrolea","municipality"=>"Junin","state"=>"Tachira"],
			["name"=>"Quinimari","municipality"=>"Junin","state"=>"Tachira"],
			["name"=>"Bramon","municipality"=>"Junin","state"=>"Tachira"],
			["name"=>"Samuel Dario Maldonado","municipality"=>"Samuel Dario Maldonado","state"=>"Tachira"],
			["name"=>"Bocono","municipality"=>"Samuel Dario Maldonado","state"=>"Tachira"],
			["name"=>"Hernandez","municipality"=>"Samuel Dario Maldonado","state"=>"Tachira"],
			["name"=>"Uribante","municipality"=>"Uribante","state"=>"Tachira"],
			["name"=>"Cardenas","municipality"=>"Uribante","state"=>"Tachira"],
			["name"=>"Juan Pablo Peñaloza","municipality"=>"Uribante","state"=>"Tachira"],
			["name"=>"Potosi","municipality"=>"Uribante","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital San Jose De Bolivar)","municipality"=>"Francisco De Miranda","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital San Josecito)","municipality"=>"Torbes","state"=>"Tachira"],
			["name"=>"Garcia De Hevia","municipality"=>"Garcia De Hevia","state"=>"Tachira"],
			["name"=>"Boca De Grita","municipality"=>"Garcia De Hevia","state"=>"Tachira"],
			["name"=>"Jose Antonio Paez","municipality"=>"Garcia De Hevia","state"=>"Tachira"],
			["name"=>"Lobatera","municipality"=>"Lobatera","state"=>"Tachira"],
			["name"=>"Constitucion","municipality"=>"Lobatera","state"=>"Tachira"],
			["name"=>"La Concordia","municipality"=>"San Cristobal","state"=>"Tachira"],
			["name"=>"Pedro Maria Morantes","municipality"=>"San Cristobal","state"=>"Tachira"],
			["name"=>"San Juan Bautista","municipality"=>"San Cristobal","state"=>"Tachira"],
			["name"=>"San Sebastian","municipality"=>"San Cristobal","state"=>"Tachira"],
			["name"=>"Dr. Francisco Romero Lobo","municipality"=>"San Cristobal","state"=>"Tachira"],
			["name"=>"Independencia","municipality"=>"Independencia","state"=>"Tachira"],
			["name"=>"Juan German Roscio","municipality"=>"Independencia","state"=>"Tachira"],
			["name"=>"Roman Cardenas","municipality"=>"Independencia","state"=>"Tachira"],
			["name"=>"No Tiene Parroquia (Capital Seboruco)","municipality"=>"Seboruco","state"=>"Tachira"],
			["name"=>"Pedro Maria Ureña","municipality"=>"Pedro Maria Ureña","state"=>"Tachira"],
			["name"=>"Nueva Arcadia","municipality"=>"Pedro Maria Ureña","state"=>"Tachira"],
			["name"=>"Pampan","municipality"=>"Pampan","state"=>"Trujillo"],
			["name"=>"Flor De Patria","municipality"=>"Pampan","state"=>"Trujillo"],
			["name"=>"La Paz","municipality"=>"Pampan","state"=>"Trujillo"],
			["name"=>"Santa Ana","municipality"=>"Pampan","state"=>"Trujillo"],
			["name"=>"Sabana De Mendoza","municipality"=>"Sucre","state"=>"Trujillo"],
			["name"=>"El Paraiso","municipality"=>"Sucre","state"=>"Trujillo"],
			["name"=>"Junin","municipality"=>"Sucre","state"=>"Trujillo"],
			["name"=>"Valmore Rodriguez","municipality"=>"Sucre","state"=>"Trujillo"],
			["name"=>"Santa Isabel","municipality"=>"Andre Bello","state"=>"Trujillo"],
			["name"=>"Araguaney","municipality"=>"Andre Bello","state"=>"Trujillo"],
			["name"=>"El Jagüito","municipality"=>"Andre Bello","state"=>"Trujillo"],
			["name"=>"La Esperanza","municipality"=>"Andre Bello","state"=>"Trujillo"],
			["name"=>"Chejende","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"Arnoldo Gabaldon","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"Bolivia","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"Carrillo","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"Cegarra","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"Manuel Salvador Ulloa","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"San Jose","municipality"=>"Candelaria","state"=>"Trujillo"],
			["name"=>"El Socorro","municipality"=>"Jose Felipe Marquez Cañizales","state"=>"Trujillo"],
			["name"=>"Antonio Jose De Sucre","municipality"=>"Jose Felipe Marquez Cañizales","state"=>"Trujillo"],
			["name"=>"Los Caprichos","municipality"=>"Jose Felipe Marquez Cañizales","state"=>"Trujillo"],
			["name"=>"El Dividive","municipality"=>"Miranda","state"=>"Trujillo"],
			["name"=>"Agua Santa","municipality"=>"Miranda","state"=>"Trujillo"],
			["name"=>"Agua Caliente","municipality"=>"Miranda","state"=>"Trujillo"],
			["name"=>"El Cenizo","municipality"=>"Miranda","state"=>"Trujillo"],
			["name"=>"Valerita","municipality"=>"Miranda","state"=>"Trujillo"],
			["name"=>"Juan Ignacio Montilla","municipality"=>"Valera","state"=>"Trujillo"],
			["name"=>"La Beatriz","municipality"=>"Valera","state"=>"Trujillo"],
			["name"=>"Mercedes Diaz","municipality"=>"Valera","state"=>"Trujillo"],
			["name"=>"San Luis","municipality"=>"Valera","state"=>"Trujillo"],
			["name"=>"La Puerta","municipality"=>"Valera","state"=>"Trujillo"],
			["name"=>"Mendoza","municipality"=>"Valera","state"=>"Trujillo"],
			["name"=>"Motatan","municipality"=>"Motatan","state"=>"Trujillo"],
			["name"=>"El Baño","municipality"=>"Motatan","state"=>"Trujillo"],
			["name"=>"Jalisco","municipality"=>"Motatan","state"=>"Trujillo"],
			["name"=>"Bocono","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"El Carmen","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Mosquey","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Ayacucho","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Burbusay","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"General Rivas","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Guaramacal","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Vega De Guaramacal","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Monseñor Jauregui","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Rafael Rangel","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"San Miguel","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"San Jose","municipality"=>"Bocono","state"=>"Trujillo"],
			["name"=>"Andre Linares","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Chiquinquira","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Cristobal Mendoza","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Cruz Carrillo","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Matriz","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Monseñor Carrillo","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Tres Esquinas","municipality"=>"Trujillo","state"=>"Trujillo"],
			["name"=>"Monte Carmelo","municipality"=>"Monte Carmelo","state"=>"Trujillo"],
			["name"=>"Buena Vista","municipality"=>"Monte Carmelo","state"=>"Trujillo"],
			["name"=>"Santa Maria Del Horcon","municipality"=>"Monte Carmelo","state"=>"Trujillo"],
			["name"=>"Carvajal","municipality"=>"San Rafael De Carvajal","state"=>"Trujillo"],
			["name"=>"Antonio Nicolas Briceño","municipality"=>"San Rafael De Carvajal","state"=>"Trujillo"],
			["name"=>"Campo Alegre","municipality"=>"San Rafael De Carvajal","state"=>"Trujillo"],
			["name"=>"Jose Leonardo Suarez","municipality"=>"San Rafael De Carvajal","state"=>"Trujillo"],
			["name"=>"Carache","municipality"=>"Carache","state"=>"Trujillo"],
			["name"=>"Cuicas","municipality"=>"Carache","state"=>"Trujillo"],
			["name"=>"La Concepcion","municipality"=>"Carache","state"=>"Trujillo"],
			["name"=>"Panamericana","municipality"=>"Carache","state"=>"Trujillo"],
			["name"=>"Santa Cruz","municipality"=>"Carache","state"=>"Trujillo"],
			["name"=>"Escuque","municipality"=>"Escuque","state"=>"Trujillo"],
			["name"=>"La Union","municipality"=>"Escuque","state"=>"Trujillo"],
			["name"=>"Sabana Libre","municipality"=>"Escuque","state"=>"Trujillo"],
			["name"=>"Santa Rita","municipality"=>"Escuque","state"=>"Trujillo"],
			["name"=>"Campo Elias","municipality"=>"Juan Vicente Campo Elias","state"=>"Trujillo"],
			["name"=>"Arnoldo Gabaldon","municipality"=>"Juan Vicente Campo Elias","state"=>"Trujillo"],
			["name"=>"Santa Apolonia","municipality"=>"La Ceiba","state"=>"Trujillo"],
			["name"=>"El Progreso","municipality"=>"La Ceiba","state"=>"Trujillo"],
			["name"=>"La Ceiba","municipality"=>"La Ceiba","state"=>"Trujillo"],
			["name"=>"Tres De Febrero","municipality"=>"La Ceiba","state"=>"Trujillo"],
			["name"=>"Betijoque","municipality"=>"Rafael Rangel","state"=>"Trujillo"],
			["name"=>"La Pueblita","municipality"=>"Rafael Rangel","state"=>"Trujillo"],
			["name"=>"Los Cedros","municipality"=>"Rafael Rangel","state"=>"Trujillo"],
			["name"=>"Jose Gregorio Hernandez","municipality"=>"Rafael Rangel","state"=>"Trujillo"],
			["name"=>"Sabana Grande","municipality"=>"Bolivar","state"=>"Trujillo"],
			["name"=>"Cheregüe","municipality"=>"Bolivar","state"=>"Trujillo"],
			["name"=>"Granados","municipality"=>"Bolivar","state"=>"Trujillo"],
			["name"=>"La Quebrada","municipality"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"Cabimbu","municipality"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"Jajo","municipality"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"La Mesa","municipality"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"Santiago","municipality"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"Tuñame","municipality"=>"Urdaneta","state"=>"Trujillo"],
			["name"=>"Pampanito","municipality"=>"Pampanito","state"=>"Trujillo"],
			["name"=>"La Concepcion","municipality"=>"Pampanito","state"=>"Trujillo"],
			["name"=>"Pampanito Ii","municipality"=>"Pampanito","state"=>"Trujillo"],
			["name"=>"No Tiene Parroquia (Capital Yumare)","municipality"=>"Manuel Monge","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Cocorote)","municipality"=>"Cocorote","state"=>"Yaracuy"],
			["name"=>"Capital Veroes","municipality"=>"Veroes","state"=>"Yaracuy"],
			["name"=>"El Guayabo","municipality"=>"Veroes","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Boraure)","municipality"=>"La Trinidad","state"=>"Yaracuy"],
			["name"=>"Capital Nirgua","municipality"=>"Nirgua","state"=>"Yaracuy"],
			["name"=>"Salom","municipality"=>"Nirgua","state"=>"Yaracuy"],
			["name"=>"Temerla","municipality"=>"Nirgua","state"=>"Yaracuy"],
			["name"=>"Capital Bruzual","municipality"=>"Bruzual","state"=>"Yaracuy"],
			["name"=>"Campo Elias","municipality"=>"Bruzual","state"=>"Yaracuy"],
			["name"=>"Capital Peña","municipality"=>"Peña","state"=>"Yaracuy"],
			["name"=>"San Andre","municipality"=>"Peña","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Independencia)","municipality"=>"Independencia","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Urachiche)","municipality"=>"Urachiche","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Guama)","municipality"=>"Sucre","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Aroa)","municipality"=>"Bolivar","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital San Pablo)","municipality"=>"Aristides Bastidas","state"=>"Yaracuy"],
			["name"=>"No Tiene Parroquia (Capital Sabana De Parra)","municipality"=>"Jose Antonio Paez","state"=>"Yaracuy"],
			["name"=>"Capital San Felipe","municipality"=>"San Felipe","state"=>"Yaracuy"],
			["name"=>"Albarico","municipality"=>"San Felipe","state"=>"Yaracuy"],
			["name"=>"San Javier","municipality"=>"San Felipe","state"=>"Yaracuy"],
			["name"=>"Jesus Maria Semprum","municipality"=>"Jesus Maria Semprum","state"=>"Zulia"],
			["name"=>"Bari","municipality"=>"Jesus Maria Semprum","state"=>"Zulia"],
			["name"=>"San Rafael","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"La Sierrita","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"Las Parcelas","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"Luis De Vicente","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"Monseñor Marcos Sergio Godoy","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"Ricaurte","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"Tamare","municipality"=>"Mara","state"=>"Zulia"],
			["name"=>"Alonso De Ojeda","municipality"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"Libertad","municipality"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"Campo Lara","municipality"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"Eleazar Lopez Contreras","municipality"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"Venezuela","municipality"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"El Danto","municipality"=>"Lagunillas","state"=>"Zulia"],
			["name"=>"Santa Rita","municipality"=>"Santa Rita","state"=>"Zulia"],
			["name"=>"El Mene","municipality"=>"Santa Rita","state"=>"Zulia"],
			["name"=>"Jose Cenovio Urribarri","municipality"=>"Santa Rita","state"=>"Zulia"],
			["name"=>"Pedro Lucas Urribarri","municipality"=>"Santa Rita","state"=>"Zulia"],
			["name"=>"Libertad","municipality"=>"Machiques De Perija","state"=>"Zulia"],
			["name"=>"Bartolome De Las Casas","municipality"=>"Machiques De Perija","state"=>"Zulia"],
			["name"=>"Rio Negro","municipality"=>"Machiques De Perija","state"=>"Zulia"],
			["name"=>"San Jose De Perija","municipality"=>"Machiques De Perija","state"=>"Zulia"],
			["name"=>"La Victoria","municipality"=>"Valmore Rodriguez","state"=>"Zulia"],
			["name"=>"Rafael Urdaneta","municipality"=>"Valmore Rodriguez","state"=>"Zulia"],
			["name"=>"Raul Cuenca","municipality"=>"Valmore Rodriguez","state"=>"Zulia"],
			["name"=>"San Carlos Del Zulia","municipality"=>"Colon","state"=>"Zulia"],
			["name"=>"Moralito","municipality"=>"Colon","state"=>"Zulia"],
			["name"=>"Santa Barbara","municipality"=>"Colon","state"=>"Zulia"],
			["name"=>"Santa Cruz Del Zulia","municipality"=>"Colon","state"=>"Zulia"],
			["name"=>"Urribarri","municipality"=>"Colon","state"=>"Zulia"],
			["name"=>"Ambrosio","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"Carmen Herrera","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"German Rios Linares","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"La Rosa","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"Jorge Hernandez","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"Romulo Betancourt","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"San Benito","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"Aristides Calvani","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"Punta Gorda","municipality"=>"Cabimas","state"=>"Zulia"],
			["name"=>"El Rosario","municipality"=>"Rosario De Perija","state"=>"Zulia"],
			["name"=>"Donaldo Garcia","municipality"=>"Rosario De Perija","state"=>"Zulia"],
			["name"=>"Sixto Zambrano","municipality"=>"Rosario De Perija","state"=>"Zulia"],
			["name"=>"Sinamaica","municipality"=>"Indigena Bolivariano Guajira","state"=>"Zulia"],
			["name"=>"Alta Guajira","municipality"=>"Indigena Bolivariano Guajira","state"=>"Zulia"],
			["name"=>"Elias Sanchez Rubio","municipality"=>"Indigena Bolivariano Guajira","state"=>"Zulia"],
			["name"=>"Guajira","municipality"=>"Indigena Bolivariano Guajira","state"=>"Zulia"],
			["name"=>"San Francisco","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"El Bajo","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Domitila Flores","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Francisco Ochoa","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Los Cortijos","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Marcial Hernandez","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Jose Domingo Rus","municipality"=>"San Francisco","state"=>"Zulia"],
			["name"=>"Isla De Toas","municipality"=>"Almirante Padilla","state"=>"Zulia"],
			["name"=>"Monagas","municipality"=>"Almirante Padilla","state"=>"Zulia"],
			["name"=>"La Concepcion","municipality"=>"Jesus Enrique Lossada","state"=>"Zulia"],
			["name"=>"Jose Ramon Yepes","municipality"=>"Jesus Enrique Lossada","state"=>"Zulia"],
			["name"=>"Mariano Parra Leon","municipality"=>"Jesus Enrique Lossada","state"=>"Zulia"],
			["name"=>"San Jose","municipality"=>"Jesus Enrique Lossada","state"=>"Zulia"],
			["name"=>"Altagracia","municipality"=>"Miranda","state"=>"Zulia"],
			["name"=>"Ana Maria Campos","municipality"=>"Miranda","state"=>"Zulia"],
			["name"=>"Faria","municipality"=>"Miranda","state"=>"Zulia"],
			["name"=>"San Antonio","municipality"=>"Miranda","state"=>"Zulia"],
			["name"=>"San Jose","municipality"=>"Miranda","state"=>"Zulia"],
			["name"=>"Jose Antonio Chaves","municipality"=>"Miranda","state"=>"Zulia"],
			["name"=>"San Timoteo","municipality"=>"Baralt","state"=>"Zulia"],
			["name"=>"General Urdaneta","municipality"=>"Baralt","state"=>"Zulia"],
			["name"=>"Libertador","municipality"=>"Baralt","state"=>"Zulia"],
			["name"=>"Manuel Guanipa Matos","municipality"=>"Baralt","state"=>"Zulia"],
			["name"=>"Marcelino Briceño","municipality"=>"Baralt","state"=>"Zulia"],
			["name"=>"Pueblo Nuevo","municipality"=>"Baralt","state"=>"Zulia"],
			["name"=>"Encontrados","municipality"=>"Catatumbo","state"=>"Zulia"],
			["name"=>"Udon Perez","municipality"=>"Catatumbo","state"=>"Zulia"],
			["name"=>"Concepcion","municipality"=>"La Cañada De Urdaneta","state"=>"Zulia"],
			["name"=>"Andre Bello","municipality"=>"La Cañada De Urdaneta","state"=>"Zulia"],
			["name"=>"Chiquinquira","municipality"=>"La Cañada De Urdaneta","state"=>"Zulia"],
			["name"=>"El Carmelo","municipality"=>"La Cañada De Urdaneta","state"=>"Zulia"],
			["name"=>"Potreritos","municipality"=>"La Cañada De Urdaneta","state"=>"Zulia"],
			["name"=>"Bobures","municipality"=>"Sucre","state"=>"Zulia"],
			["name"=>"El Batey","municipality"=>"Sucre","state"=>"Zulia"],
			["name"=>"Gibraltar","municipality"=>"Sucre","state"=>"Zulia"],
			["name"=>"Heras","municipality"=>"Sucre","state"=>"Zulia"],
			["name"=>"Monseñor Arturo Celestino Alvarez","municipality"=>"Sucre","state"=>"Zulia"],
			["name"=>"Romulo Gallegos","municipality"=>"Sucre","state"=>"Zulia"],
			["name"=>"Manuel Manrique","municipality"=>"Simon Bolivar","state"=>"Zulia"],
			["name"=>"Rafael Maria Baralt","municipality"=>"Simon Bolivar","state"=>"Zulia"],
			["name"=>"Rafael Urdaneta","municipality"=>"Simon Bolivar","state"=>"Zulia"],
			["name"=>"Simon Rodriguez","municipality"=>"Francisco Javier Pulgar","state"=>"Zulia"],
			["name"=>"Carlos Quevedo","municipality"=>"Francisco Javier Pulgar","state"=>"Zulia"],
			["name"=>"Francisco Javier Pulgar","municipality"=>"Francisco Javier Pulgar","state"=>"Zulia"],
			["name"=>"Agustin Codazzi","municipality"=>"Francisco Javier Pulgar","state"=>"Zulia"],
			["name"=>"Antonio Borjas Romero","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Bolivar","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Cacique Mara","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Caracciolo Parra Perez","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Cecilio Acosta","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Cristo De Aranza","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Coquivacoa","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Chiquinquira","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Francisco Eugenio Bustamante","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Idelfonso Vasquez","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Juana De ├Üvila","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Luis Hurtado Higuera","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Manuel Dagnino","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Olegario Villalobos","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Raul Leoni","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Santa Lucia","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Venancio Pulgar","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"San Isidro","municipality"=>"Maracaibo","state"=>"Zulia"],
			["name"=>"Caraballeda","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Carayaca","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Caruao","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Catia La Mar","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"El Junko","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"La Guaira","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Macuto","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Maiquetia","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Naiguata","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Urimare","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Carlos Soublette","municipality"=>"Vargas","state"=>"La Guaira"],
			["name"=>"Atabapo","municipality"=>"Autonomo Atabapo","state"=>"Amazonas"],
			["name"=>"Caname","municipality"=>"Autonomo Atabapo","state"=>"Amazonas"],
			["name"=>"Casiquiare","municipality"=>"Autonomo Rio Negro","state"=>"Amazonas"],
			["name"=>"Cocuy","municipality"=>"Autonomo Rio Negro","state"=>"Amazonas"],
			["name"=>"Solano","municipality"=>"Autonomo Rio Negro","state"=>"Amazonas"],
			["name"=>"Sipapo","municipality"=>"Autonomo Autana","state"=>"Amazonas"],
			["name"=>"Munduapo","municipality"=>"Autonomo Autana","state"=>"Amazonas"],
			["name"=>"Isla Ratón","municipality"=>"Autonomo Autana","state"=>"Amazonas"],
			["name"=>"La Esmeralda","municipality"=>"Autonomo Alto Orinoco","state"=>"Amazonas"],
			["name"=>"Marawaka","municipality"=>"Autonomo Alto Orinoco","state"=>"Amazonas"],
			["name"=>"Mavaka","municipality"=>"Autonomo Alto Orinoco","state"=>"Amazonas"],
			["name"=>"Sierra Parima","municipality"=>"Autonomo Alto Orinoco","state"=>"Amazonas"],
			["name"=>"Bajo Ventuari","municipality"=>"Autonomo Manapiare","state"=>"Amazonas"],
			["name"=>"Manapiare","municipality"=>"Autonomo Manapiare","state"=>"Amazonas"]
		];

        foreach ($parishes as $parish) {
            $state = State::where("name", $parish['state'])->first();
            $municipality = Municipality::where('name', $parish['municipality'])
                ->where('state_id', $state->id)
                ->first();
            Parish::create([
                'name' => $parish['name'],
                'municipality_id' => $municipality->id
            ]);
        }
    }
}