<?php

namespace App\Filament\Widgets;

use Filament\Widgets\StatsOverviewWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class ColegioUsuario extends StatsOverviewWidget
{
    protected static bool $isLazy = false;

    protected static ?int $sort = 2;

    public static function canView(): bool
    {
        return ! isAdmin() && Auth::user()->colegios_id; // TODO: Change the autogenerated stub
    }

    protected function getStats(): array
    {
        $nombreColegio = Auth::user()->colegio?->nombre ?? 'Sin Institución';

        return [
            Stat::make('Colegio', Str::upper($nombreColegio))
                ->description('Asignado para el usuario actual')
                ->color('violet')
                ->columnSpanFull(),
        ];
    }
}
