<?php

namespace App\Filament\Widgets;

use App\Filament\Resources\Colegios\ColegioResource;
use App\Filament\Resources\Deportes\DeporteResource;
use App\Filament\Resources\Users\UserResource;
use App\Models\Colegio;
use App\Models\Deporte;
use App\Models\User;
use Filament\Support\Enums\IconPosition;
use Filament\Support\Icons\Heroicon;
use Filament\Widgets\StatsOverviewWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class SistemaStats extends StatsOverviewWidget
{
    protected static bool $isLazy = false;

    protected static ?int $sort = 1;

    public static function canView(): bool
    {
        return isAdmin(); // TODO: Change the autogenerated stub
    }

    protected function getStats(): array
    {
        return [
            Stat::make('Colegios', Colegio::count())
                ->description('Instituciones registradas')
                ->descriptionIcon(Heroicon::OutlinedAcademicCap, position: IconPosition::Before)
                ->color('info')
                ->url(ColegioResource::getUrl('index')),

            Stat::make('Deportes', Deporte::where('is_active', true)->count())
                ->description('Disciplinas disponibles')
                ->descriptionIcon(Heroicon::OutlinedTrophy, position: IconPosition::Before)
                ->color('warning')
                ->url(DeporteResource::getUrl('index')),

            Stat::make('Usuarios', User::where('is_active', true)->count())
                ->description('Cuentas activas')
                ->descriptionIcon(Heroicon::OutlinedUsers, position: IconPosition::Before)
                ->color('success')
                ->url(UserResource::getUrl('index')),
        ];
    }
}
